/**
 * Advancement engine (Task CB-2, monorepo docs/CHARACTER_BUILDER_PLAN_2026-07-24.md).
 *
 * Pure functions over schema-v4 character documents + the chargen data pack
 * (api/data/chargen/pack.mjs — corpus-derived, prose-stripped). Exposed
 * through dispatch (`/api/chargen/*`), so the Pages Builder UI today and the
 * rogue-trader-2e Foundry sheet later consume the IDENTICAL cost/prerequisite
 * logic — the one-rules-brain law applied to advancement.
 *
 * DH2 cost rule (corpus data/advancement.json, Tables 2-2/2-4/2-6):
 * cost = f(kind, rank/tier, aptitude matches 0|1|2). "all characters in DARK
 * HERESY have the General aptitude" (core p.79-book) — General always counts.
 * Characteristics have 5 advance ranks (Simple→Expert); skills 4
 * (Known→Veteran); talents cost by tier; psy rating = 200 × new rating.
 *
 * Ledger discipline (decision D-I): applyAdvance mutates NOTHING — it returns
 * a deep-copied doc with the mechanical change AND a typed ledger entry
 * appended atomically. Advance COUNTS stay authoritative for play;
 * validateBuild reconciles ledger↔counts (errors only when the ledger is
 * fully typed, i.e. builder-written; warnings on legacy docs).
 */
import {
    characteristicTotal, canonicalSkillName, SKILL_DEFS, LEDGER_KINDS,
} from './character-schema.mjs';

const CHAR_KEY_BY_NAME = {
    'weapon skill': 'ws', 'ballistic skill': 'bs', 'strength': 's', 'toughness': 't',
    'agility': 'ag', 'intelligence': 'int', 'perception': 'per', 'willpower': 'wp',
    'fellowship': 'fel',
};

/**
 * PACK KEY → DOCUMENT KEY, for characteristics (finding D-1).
 *
 * The chargen pack (api/data/chargen/pack.mjs) is GENERATED by
 * `npm run sync:chargen` from the T1 corpus (dark_heresy_2e
 * data/advancement.json), which keys willpower `wil`. Character documents key
 * it `wp` (character-schema.mjs CHARACTERISTIC_KEYS, CHAR_KEY_BY_NAME above).
 * NEITHER side may be renamed: the pack is overwritten on every sync, and the
 * corpus is governed by the fidelity protocol. So the two vocabularies are
 * reconciled HERE, at the single consumer boundary — the pack's key is
 * translated on the way in, and only DOCUMENT keys ever leave this module
 * (advance.ref, ledger entry.ref). A re-sync of pack.mjs cannot reintroduce
 * the defect; a NEW divergence would, which advancement-fixes.test.mjs guards.
 *
 * Keys absent from this table pass through unchanged (ws/bs/s/t/ag/int/per/fel
 * agree today) — as does `wp` itself, so the table stays correct if the corpus
 * is ever renamed to match.
 */
const DOC_CHAR_KEY_BY_PACK_KEY = {
    wil: 'wp',      // corpus "wil" (advancement.json aptitude table) → document "wp"
};
/** The document characteristic key for a pack/ledger characteristic key. */
export const docCharKey = (packKey) => DOC_CHAR_KEY_BY_PACK_KEY[packKey] ?? packKey;
const norm = (s) => String(s ?? '').trim().toLowerCase();
const entryName = (e) => (e && typeof e === 'object') ? String(e.name ?? '') : String(e ?? '');

/** The character's aptitude name set (lowercased). General is always held. */
export function aptitudeSet(doc) {
    const set = new Set(['general']);
    for (const a of doc.aptitudes ?? []) set.add(norm(entryName(a)));
    return set;
}

/** Matches (0|1|2) between the character's aptitudes and an advance's pair. */
export function aptitudeMatches(doc, itemAptitudes) {
    const have = aptitudeSet(doc);
    const wanted = new Set((itemAptitudes ?? []).map(norm));   // duplicates never double-count
    let n = 0;
    for (const a of wanted) if (have.has(a)) n++;
    return Math.min(2, n);
}

/**
 * XP cost of one advance. `spec`:
 *  - { kind:'characteristic', matches, rank 1..5 }
 *  - { kind:'skill',          matches, rank 1..4 }
 *  - { kind:'talent',         matches, tier 1..3 }
 *  - { kind:'psy_rating',     rank: newRating }
 *  - { kind:'elite_advance',  cost }               (per-entry xpCost)
 * Throws on out-of-range input.
 */
export function advanceCost(pack, spec) {
    const band = (m) => {
        if (![0, 1, 2].includes(m)) throw new Error(`matches must be 0|1|2, got ${m}`);
        return `matches_${m}`;
    };
    switch (spec.kind) {
        case 'characteristic': {
            const col = pack.costs.characteristic[band(spec.matches)];
            if (!Number.isInteger(spec.rank) || spec.rank < 1 || spec.rank > col.length) throw new Error(`characteristic rank must be 1..${col.length}, got ${spec.rank}`);
            return col[spec.rank - 1];
        }
        case 'skill': {
            const col = pack.costs.skill[band(spec.matches)];
            if (!Number.isInteger(spec.rank) || spec.rank < 1 || spec.rank > col.length) throw new Error(`skill rank must be 1..${col.length}, got ${spec.rank}`);
            return col[spec.rank - 1];
        }
        case 'talent': {
            const tier = pack.costs.talent[`tier_${spec.tier}`];
            if (!tier) throw new Error(`talent tier must be 1..3, got ${spec.tier}`);
            return tier[band(spec.matches)];
        }
        case 'psy_rating': {
            if (!Number.isInteger(spec.rank) || spec.rank < 1) throw new Error(`psy rating must be ≥ 1, got ${spec.rank}`);
            return pack.costs.psyRating.perRating * spec.rank;
        }
        case 'elite_advance': {
            if (!Number.isInteger(spec.cost) || spec.cost < 0) throw new Error('elite advance needs its entry xpCost');
            return spec.cost;
        }
        default:
            throw new Error(`unknown advance kind "${spec.kind}"`);
    }
}

/** { total, spent, remaining } — spent is ALWAYS the ledger sum. */
export function xpSummary(doc) {
    const total = doc.xp?.total ?? 0;
    const spent = (doc.xp?.ledger ?? []).reduce((a, e) => a + (e.cost || 0), 0);
    return { total, spent, remaining: total - spent };
}

/**
 * Prerequisite check against the doc. Parses the common corpus patterns:
 * characteristic thresholds ("Ag 30"), psy rating ("Psy Rating 2"), talent
 * names (incl. "(X)" specialisations), and " or "-joined alternatives.
 * Unparseable prose → a `problems` note (advisory), never a hard block.
 * Returns { met, problems[] }.
 */
export function checkPrerequisites(doc, prerequisites) {
    const problems = [];
    let met = true;
    const talentNames = (doc.talents ?? []).map((t) => norm(entryName(t)));
    const checkOne = (p) => {
        const s = String(p).trim();
        const chr = s.match(/^(ws|bs|s|t|ag|int|per|wp|fel|weapon skill|ballistic skill|strength|toughness|agility|intelligence|perception|willpower|fellowship)\s+(\d+)$/i);
        if (chr) {
            const key = CHAR_KEY_BY_NAME[norm(chr[1])] ?? norm(chr[1]);
            return characteristicTotal(doc, key) >= Number(chr[2]);
        }
        const psy = s.match(/^psy rating (\d+)$/i);
        if (psy) return (doc.psy?.rating ?? 0) >= Number(psy[1]);
        // EA-entry vocabularies (2026-08-26): Influence thresholds, elite-
        // advance gates (both directions), and background requirements.
        const inf = s.match(/^influence\s+(\d+)$/i);
        if (inf) return (doc.influence ?? 0) >= Number(inf[1]);
        const heldEa = (name) => (doc.origin?.eliteAdvances ?? [])
            .some((e) => norm(entryName(e)) === norm(name));
        const noEa = s.match(/^no\s+(.+?)\s+elite advance\b/i);
        if (noEa) return !heldEa(noEa[1]);
        const ea = s.match(/^(.+?)\s+elite advance$/i);
        if (ea) return heldEa(ea[1]);
        const bg = s.match(/^(.+?)\s+background$/i);
        if (bg) return norm(entryName(doc.origin?.background ?? '')) === norm(bg[1]);
        const base = norm(s).replace(/\s*\(.*\)$/, '');
        if (talentNames.some((n) => n === norm(s) || n.replace(/\s*\(.*\)$/, '') === base)) return true;
        return null;                                        // unparseable / not held
    };
    for (const p of prerequisites ?? []) {
        const alternatives = String(p).split(/\s+or\s+/i);
        const results = alternatives.map(checkOne);
        if (results.some((r) => r === true)) continue;
        if (results.every((r) => r === null)) {
            // could be prose we can't parse OR a talent simply not held; flag,
            // don't block (plan CB-2.1: warn-and-confirm pattern)
            problems.push(`unverified prerequisite: "${p}"`);
            continue;
        }
        met = false;
        problems.push(`unmet prerequisite: "${p}"`);
    }
    return { met, problems };
}

const skillEntryFor = (doc, canonical) => {
    const key = Object.keys(doc.skills ?? {}).find((k) => canonicalSkillName(k) === canonical);
    return key ? doc.skills[key] : null;
};

/**
 * Every advance the character could buy next, cost-annotated.
 * Returns [{ kind, ref, name, rank?, tier?, matches, cost, affordable,
 *            prereqsMet, prereqProblems[], speciality? }].
 * Skills: known specialities advance individually; specialist skills also
 * offer a "new speciality" template entry (rank 1, speciality: null).
 */
export function listAvailableAdvances(doc, pack) {
    const { remaining } = xpSummary(doc);
    const out = [];
    const push = (a) => out.push({ ...a, affordable: a.cost <= remaining });

    // characteristics — next rank each (max = table length, 5)
    for (const [packKey, aptPair] of Object.entries(pack.characteristicAptitudes)) {
        const key = docCharKey(packKey);                  // D-1: pack "wil" → doc "wp"
        const c = doc.characteristics?.[key];
        const cur = (typeof c === 'number' ? 0 : c?.advances) ?? 0;   // compact scalar form = 0 advances
        const max = pack.costs.characteristic.matches_2.length;
        if (cur >= max) continue;
        const matches = aptitudeMatches(doc, aptPair);
        push({
            kind: 'characteristic', ref: key, name: `${key.toUpperCase()} advance ${cur + 1}`,
            rank: cur + 1, matches,
            cost: advanceCost(pack, { kind: 'characteristic', matches, rank: cur + 1 }),
            prereqsMet: true, prereqProblems: [],
        });
    }

    // skills — next rank per known entry/speciality; new-speciality template
    for (const s of pack.skills) {
        const matches = aptitudeMatches(doc, s.aptitudes);
        const canonical = canonicalSkillName(s.name);
        const entry = canonical ? skillEntryFor(doc, canonical) : null;
        const nextFor = (advances, speciality) => {
            if (advances >= 4) return;
            push({
                kind: 'skill', ref: s.ref, name: speciality ? `${s.name} (${speciality})` : s.name,
                rank: advances + 1, matches, speciality: speciality ?? undefined,
                cost: advanceCost(pack, { kind: 'skill', matches, rank: advances + 1 }),
                prereqsMet: true, prereqProblems: [],
            });
        };
        if (s.specialist) {
            for (const [spec, sv] of Object.entries(entry?.specialities ?? {})) nextFor(sv.advances ?? 0, spec);
            push({
                kind: 'skill', ref: s.ref, name: `${s.name} (new speciality)`, rank: 1,
                matches, speciality: null,
                cost: advanceCost(pack, { kind: 'skill', matches, rank: 1 }),
                prereqsMet: true, prereqProblems: [],
            });
        } else {
            nextFor(entry?.advances ?? 0, null);
        }
    }

    // talents — not already held (non-specialist), prereq-checked. Talents
    // carrying `eliteAdvance` are UNLOCKED ADVANCES (core p.86): hidden until
    // the gating elite advance is held.
    const heldEAs = new Set((doc.origin?.eliteAdvances ?? []).map((e) => norm(entryName(e))));
    const held = new Set((doc.talents ?? []).map((t) => norm(entryName(t)).replace(/\s*\(.*\)$/, '')));
    for (const t of pack.talents) {
        if (t.eliteAdvance) {
            const gate = pack.eliteAdvances.find((e) => e.id === t.eliteAdvance);
            if (!gate || !heldEAs.has(norm(gate.name))) continue;
        }
        if (!t.specialist && held.has(norm(t.name))) continue;
        const matches = aptitudeMatches(doc, t.aptitudes);
        const { met, problems } = checkPrerequisites(doc, t.prerequisites);
        push({
            kind: 'talent', ref: t.ref, name: t.name, tier: t.tier, matches,
            ...(t.specialist && { specialist: true }),   // needs a sub-selection to buy
            cost: advanceCost(pack, { kind: 'talent', matches, tier: t.tier }),
            prereqsMet: met, prereqProblems: problems,
        });
    }

    // psy rating — psykers only (rating > 0 or Psyker elite advance held)
    const isPsyker = (doc.psy?.rating ?? 0) > 0
        || (doc.origin?.eliteAdvances ?? []).some((e) => /psyker/i.test(entryName(e)));
    if (isPsyker) {
        const next = (doc.psy?.rating ?? 0) + 1;
        push({
            kind: 'psy_rating', ref: 'psy.rating', name: `Psy Rating ${next}`, rank: next,
            matches: 0,
            cost: advanceCost(pack, { kind: 'psy_rating', rank: next }),
            prereqsMet: true, prereqProblems: [],
        });
    }

    // elite advances — not already taken
    for (const e of pack.eliteAdvances) {
        if (heldEAs.has(norm(e.name)) || e.xpCost == null) continue;
        const { met, problems } = checkPrerequisites(doc,
            typeof e.prerequisites === 'string' ? [e.prerequisites] : e.prerequisites);
        push({
            kind: 'elite_advance', ref: e.ref, name: e.name, matches: 0, cost: e.xpCost,
            prereqsMet: met, prereqProblems: problems,
        });
    }

    return out;
}

const today = () => new Date().toISOString().slice(0, 10);

/**
 * Parse an elite advance's `instantChanges` bullets (short mechanical
 * paraphrases, the corpus convention) into structured grants. Anything the
 * patterns cannot claim becomes a `note` grant — recorded in the ledger, never
 * silently dropped (e.g. the Psyker↔Untouchable exclusion clauses).
 */
export function eliteGrants(ea) {
    const grants = [];
    for (const raw of ea?.instantChanges ?? []) {
        const s = String(raw).trim();
        let m;
        if ((m = s.match(/^gains?\s+(?:the\s+)?(.+?)\s+trait\b/i))) grants.push({ kind: 'trait', name: m[1], raw: s });
        else if ((m = s.match(/^gains?\s+(?:the\s+)?(.+?)\s+talent\b/i))) grants.push({ kind: 'talent', name: m[1], raw: s });
        else if ((m = s.match(/^gains?\s+(?:the\s+)?(.+?)\s+aptitude\b/i))) grants.push({ kind: 'aptitude', name: m[1], raw: s });
        else if ((m = s.match(/^gains?\s+(?:a\s+|the\s+)?psy rating\s+(?:of\s+)?(\d+)/i))) grants.push({ kind: 'psy_rating', rating: Number(m[1]), raw: s });
        else if ((m = s.match(/^gains?\s+(?:the\s+)?(.+?)\s+skill\b(?:.*?\brank\s+(\d+))?/i))) {
            // "Scholastic Lore (Tactica Imperialis)" → specialist skill + speciality
            const spec = m[1].match(/^(.+?)\s*\(([^)]+)\)\s*$/);
            grants.push({
                kind: 'skill', name: spec ? spec[1] : m[1],
                ...(spec && { speciality: spec[2] }),
                rank: m[2] ? Number(m[2]) : 1, raw: s,
            });
        } else grants.push({ kind: 'note', text: s, raw: s });
    }
    return grants;
}

/** Mutating core of applyGrant — shared with the elite-advance purchase path. */
function applyGrantTo(d, pack, grant, source) {
    const aptSource = /^elite advance/i.test(source) ? 'elite_advance' : 'extra';
    let label = grant.name ?? grant.text ?? '';
    let ledgerKind = 'other';
    switch (grant.kind) {
        case 'talent':
            if (!(d.talents ?? []).some((t) => norm(entryName(t)) === norm(grant.name)))
                (d.talents ??= []).push({ name: grant.name, ...(grant.ref && { ref: grant.ref }) });
            ledgerKind = 'talent';
            break;
        case 'trait':
            if (!(d.traits ?? []).some((t) => norm(entryName(t)) === norm(grant.name)))
                (d.traits ??= []).push({ name: grant.name, ...(grant.ref && { ref: grant.ref }) });
            break;
        case 'aptitude':
            if (!(d.aptitudes ?? []).some((a) => norm(entryName(a)) === norm(grant.name)))
                (d.aptitudes ??= []).push({ name: grant.name, source: aptSource });
            break;
        case 'skill': {
            const canonical = canonicalSkillName(grant.name);
            if (!canonical) throw new Error(`unknown skill "${grant.name}"`);
            d.skills ??= {};
            const rank = grant.rank ?? 1;
            if (grant.speciality) {
                const entry = (d.skills[canonical] ??= { specialities: {} });
                entry.specialities ??= {};
                const sv = (entry.specialities[grant.speciality] ??= { advances: 0 });
                sv.advances = Math.max(sv.advances ?? 0, rank);
            } else {
                const entry = (d.skills[canonical] ??= { advances: 0 });
                entry.advances = Math.max(entry.advances ?? 0, rank);
            }
            label = grant.speciality ? `${canonical} (${grant.speciality})` : canonical;
            ledgerKind = 'skill';
            break;
        }
        case 'psy_rating':
            d.psy ??= { rating: 0, class: 'none', sustained: 0 };
            d.psy.rating = Math.max(d.psy.rating ?? 0, grant.rating ?? 1);
            if (d.psy.class === 'none') d.psy.class = 'bound';
            label = `Psy Rating ${d.psy.rating}`;
            ledgerKind = 'psy_rating';
            break;
        case 'note':
            break;
        default:
            throw new Error(`unknown grant kind "${grant.kind}"`);
    }
    const entry = {
        name: label, cost: 0, kind: ledgerKind,
        grantKind: grant.kind,                 // what to re-apply on replay
        ...(grant.ref && { ref: grant.ref }),
        ...(grant.rank !== undefined && { rank: grant.rank }),
        ...(grant.kind === 'psy_rating' && grant.rating !== undefined && { rank: grant.rating }),
        ...(grant.speciality && { speciality: grant.speciality }),
        source, date: today(),
    };
    d.xp ??= { total: 0, ledger: [] };
    (d.xp.ledger ??= []).push(entry);
    return entry;
}

/**
 * Add content OUTSIDE the purchase rules: elite-advance instant changes, GM
 * gifts, and the manual override door. No XP is spent, no prerequisite is
 * checked — the ledger records the addition at 0 XP with the caller's source
 * note, so the audit trail says exactly how it got there.
 * grant: { kind: 'talent'|'trait'|'aptitude'|'skill'|'psy_rating'|'note',
 *          name?, ref?, rank?, speciality?, rating?, text? }
 */
export function applyGrant(doc, pack, grant, { source = 'grant' } = {}) {
    const d = structuredClone(doc);
    const entry = applyGrantTo(d, pack, grant, source);
    return { doc: d, entry };
}

/**
 * Buy one advance: returns { doc, entry } where doc is a DEEP COPY with the
 * mechanical change applied and the typed ledger entry appended atomically.
 * `advance` is an element of listAvailableAdvances (or the same shape).
 * Throws on: unaffordable, rank-skipping, duplicate talent/elite, non-psyker
 * psy purchase. Unmet PARSED prerequisites throw unless `confirmed: true`
 * (unverifiable prose prerequisites never block — warn-and-confirm).
 */
export function applyAdvance(doc, pack, advance, { confirmed = false, override = false, source } = {}) {
    const d = structuredClone(doc);
    if (advance.prereqsMet === false && !confirmed && !override) throw new Error(`prerequisites unmet: ${(advance.prereqProblems ?? []).join('; ')} (pass confirmed:true to override)`);
    // ONE name for the mechanical write and the ledger entry (finding D-3): a
    // speciality purchase is recorded as "Skill (Speciality)". The listing's
    // "(new speciality)" placeholder is replaced by the speciality actually
    // chosen, so validateBuild can address the doc slot the purchase wrote.
    const purchasedName = advance.speciality
        ? `${String(advance.name ?? '').replace(/\s*\([^)]*\)\s*$/, '')} (${advance.speciality})`
        : advance.name;

    // kind-specific validation (duplicates, rank sequence) runs BEFORE the XP
    // gate so the user sees the more specific error; d is a discardable clone.
    switch (advance.kind) {
        case 'characteristic': {
            // D-1: tolerate the corpus key ("wil") from stored advances / older
            // clients — it is written to the DOCUMENT key ("wp") either way.
            const key = docCharKey(advance.ref);
            let c = d.characteristics[key];
            if (typeof c === 'number') {                     // compact scalar form → canonical
                c = d.characteristics[key] = { base: c, advances: 0, modifiers: [] };
            }
            if (!c) throw new Error(`unknown characteristic "${advance.ref}"`);
            if ((c.advances ?? 0) + 1 !== advance.rank) throw new Error(`rank ${advance.rank} skips (current advances: ${c.advances ?? 0})`);
            c.advances = advance.rank;
            break;
        }
        case 'skill': {
            const packSkill = pack.skills.find((s) => s.ref === advance.ref);
            const canonical = canonicalSkillName(packSkill?.name ?? '');
            if (!canonical) throw new Error(`unknown skill ref "${advance.ref}"`);
            d.skills ??= {};
            if (packSkill.specialist) {
                if (!advance.speciality) throw new Error('specialist skill advance needs a speciality');
                const entry = (d.skills[canonical] ??= { specialities: {} });
                entry.specialities ??= {};
                const sv = (entry.specialities[advance.speciality] ??= { advances: 0 });
                if ((sv.advances ?? 0) + 1 !== advance.rank) throw new Error(`rank ${advance.rank} skips (current: ${sv.advances ?? 0})`);
                sv.advances = advance.rank;
            } else {
                const entry = (d.skills[canonical] ??= { advances: 0 });
                if ((entry.advances ?? 0) + 1 !== advance.rank) throw new Error(`rank ${advance.rank} skips (current: ${entry.advances ?? 0})`);
                entry.advances = advance.rank;
            }
            break;
        }
        case 'talent': {
            // Specialist talents (Weapon Training, Peer, Hatred, …) need a
            // sub-selection, exactly like specialist skills — the spec rides
            // the NAME ("Weapon Training (Las)"), which is also what the
            // DSL's prefix matching keys on.
            const packTalent = pack.talents.find((t) => t.ref === advance.ref);
            if (packTalent?.specialist && !advance.speciality && !/\(.+\)\s*$/.test(String(advance.name ?? ''))) {
                throw new Error('specialist talent needs a specialization');
            }
            const name = purchasedName;
            const held = (d.talents ?? []).some((t) => norm(entryName(t)) === norm(name));
            if (held) throw new Error(`talent already held: ${name}`);
            (d.talents ??= []).push({ name, ref: advance.ref });
            break;
        }
        case 'psy_rating': {
            d.psy ??= { rating: 0, class: 'bound', sustained: 0 };
            if (d.psy.rating + 1 !== advance.rank) throw new Error(`psy rating ${advance.rank} skips (current: ${d.psy.rating})`);
            d.psy.rating = advance.rank;
            if (d.psy.class === 'none') d.psy.class = 'bound';
            break;
        }
        case 'elite_advance': {
            d.origin ??= { homeworld: null, background: null, role: null, eliteAdvances: [] };
            (d.origin.eliteAdvances ??= []).push({ name: advance.name, ref: advance.ref, cost: advance.cost });
            break;
        }
        default:
            throw new Error(`unknown advance kind "${advance.kind}"`);
    }

    const { remaining } = xpSummary(doc);
    if (advance.cost > remaining) throw new Error(`insufficient XP: cost ${advance.cost}, remaining ${remaining}`);

    const entry = {
        name: purchasedName,
        cost: advance.cost,
        kind: advance.kind,
        ref: advance.ref,
        ...(advance.rank !== undefined && { rank: advance.rank }),
        ...(advance.matches !== undefined && { matches: advance.matches }),
        // every purchase carries a source note; an override says so loudly
        source: override
            ? `${source ?? 'Advancement'} [manual override — prerequisites bypassed]`
            : (source ?? 'Advancement'),
        date: today(),
    };
    d.xp ??= { total: 0, ledger: [] };
    (d.xp.ledger ??= []).push(entry);

    // Elite advances apply their INSTANT CHANGES (core p.86) on purchase —
    // each lands as a 0-XP ledger grant sourced to the advance.
    if (advance.kind === 'elite_advance') {
        const packEa = pack.eliteAdvances.find((e) => e.ref === advance.ref);
        for (const g of eliteGrants(packEa)) {
            // a grant the doc cannot take mechanically (unknown skill name,
            // future grant kinds) degrades to a ledger NOTE — the purchase
            // never aborts, and the audit trail still shows the clause
            try { applyGrantTo(d, pack, g, `Elite Advance: ${advance.name}`); }
            catch { applyGrantTo(d, pack, { kind: 'note', text: g.raw ?? g.name }, `Elite Advance: ${advance.name}`); }
        }
    }
    return { doc: d, entry };
}

/**
 * Character-creation origin application: homeworld (aptitude, fate threshold,
 * Emperor's Blessing, wounds formula returned for the UI to roll), background
 * (granted skills/talents + starting aptitude — "X or Y" grants resolved via
 * `choices`), role (aptitudes; "X or Y" via `choices`; talent choice via
 * `choices.roleTalent`). Characteristic GENERATION (the 2d10+25 rolls and the
 * homeworld's +/− roll advantage) is a Builder-UI step (decision D-K) — this
 * function records `characteristicModifiers` info without touching scores.
 * Returns { doc, woundsFormula, fateThreshold, emperorsBlessing, choicesNeeded[] }.
 */
export function applyOrigin(doc, pack, { homeworldRef, backgroundRef, roleRef, choices = {} } = {}) {
    const d = structuredClone(doc);
    const find = (list, r) => list.find((e) => e.ref === r) ?? null;
    const hw = homeworldRef ? find(pack.homeworlds, homeworldRef) : null;
    const bg = backgroundRef ? find(pack.backgrounds, backgroundRef) : null;
    const role = roleRef ? find(pack.roles, roleRef) : null;
    for (const [ref, hit, label] of [[homeworldRef, hw, 'homeworld'], [backgroundRef, bg, 'background'], [roleRef, role, 'role']]) {
        if (ref && !hit) throw new Error(`unknown ${label} ref "${ref}"`);
    }
    const choicesNeeded = [];
    d.origin ??= { homeworld: null, background: null, role: null, eliteAdvances: [] };
    d.aptitudes ??= [];
    const grantAptitude = (name, source) => {
        if (!name) return;
        if (/\s+or\s+/i.test(name)) {
            const pick = choices[name];
            if (!pick) { choicesNeeded.push({ kind: 'aptitude', options: name.split(/\s+or\s+/i), key: name, source }); return; }
            name = pick;
        }
        // duplicate aptitude → the player picks another (RAW); surface as a choice
        if (d.aptitudes.some((a) => norm(entryName(a)) === norm(name))) {
            choicesNeeded.push({ kind: 'duplicate_aptitude', duplicate: name, source });
            return;
        }
        d.aptitudes.push({ name, source });
    };

    if (hw) {
        d.origin.homeworld = { name: hw.name, ref: hw.ref };
        grantAptitude(hw.aptitude, 'homeworld');
        d.fate = { max: hw.fateThreshold, current: hw.fateThreshold };   // +1 on Emperor's Blessing (UI rolls it)
    }
    if (bg) {
        d.origin.background = { name: bg.name, ref: bg.ref };
        grantAptitude(bg.startingAptitude, 'background');
        d.skills ??= {};
        for (const grant of bg.skillsGranted) {
            let g = grant;
            if (/\s+or\s+/i.test(g)) {
                const pick = choices[g];
                if (!pick) { choicesNeeded.push({ kind: 'skill', options: g.split(/\s+or\s+/i), key: g, source: 'background' }); continue; }
                g = pick;
            }
            const m = g.match(/^([^(]+?)\s*\(([^)]+)\)\s*$/);
            const canonical = canonicalSkillName(m ? m[1] : g);
            if (!canonical) { choicesNeeded.push({ kind: 'unresolved_skill', grant: g, source: 'background' }); continue; }
            if (SKILL_DEFS[canonical].specialist) {
                const spec = m ? m[2] : null;
                if (!spec) { choicesNeeded.push({ kind: 'speciality', skill: canonical, key: g, source: 'background' }); continue; }
                const entry = (d.skills[canonical] ??= { specialities: {} });
                entry.specialities ??= {};
                entry.specialities[spec] = { advances: Math.max(1, entry.specialities[spec]?.advances ?? 0) };
            } else {
                const entry = (d.skills[canonical] ??= { advances: 0 });
                entry.advances = Math.max(1, entry.advances ?? 0);
            }
        }
        for (const grant of bg.talentsGranted) {
            let g = grant;
            if (/\s+or\s+/i.test(g)) {
                const pick = choices[g];
                if (!pick) { choicesNeeded.push({ kind: 'talent', options: g.split(/\s+or\s+/i), key: g, source: 'background' }); continue; }
                g = pick;
            }
            if (!(d.talents ?? []).some((t) => norm(entryName(t)) === norm(g))) (d.talents ??= []).push({ name: g });
        }
    }
    if (role) {
        d.origin.role = { name: role.name, ref: role.ref };
        for (const apt of role.roleAptitudes) grantAptitude(apt, 'role');
        const pick = choices.roleTalent;
        if (role.roleTalentChoice?.length) {
            if (!pick) choicesNeeded.push({ kind: 'talent', options: role.roleTalentChoice, key: 'roleTalent', source: 'role' });
            else if (!(d.talents ?? []).some((t) => norm(entryName(t)) === norm(pick))) (d.talents ??= []).push({ name: pick });
        }
    }
    d.xp ??= { total: 0, ledger: [] };
    if (!d.xp.total) d.xp.total = pack.startingXp;

    return {
        doc: d,
        woundsFormula: hw?.woundsFormula ?? null,
        fateThreshold: hw?.fateThreshold ?? null,
        emperorsBlessing: hw?.emperorsBlessing ?? null,
        characteristicModifiers: hw?.characteristicModifiers ?? {},
        choicesNeeded,
    };
}

/**
 * Resolve a typed SKILL ledger entry to the document slot the purchase should
 * have written (finding D-3) → { label, got }: the label used in the message
 * and the advance count the document actually holds. Returns null when the
 * entry names no DH2 core skill (homebrew, or a corpus rename): unresolvable
 * entries are SKIPPED rather than guessed at — a false error is worse than
 * silence, and the same policy already applies to non-pack talents below.
 *
 * Entry names are "Skill" or "Skill (Speciality)" — applyAdvance writes the
 * second form for every speciality purchase. A specialist entry whose name
 * carries no usable speciality (ledgers written before that fix, hand-made
 * imports) cannot address one slot, so it reconciles against the HIGHEST
 * speciality advance held: genuine drift still surfaces, a real build never
 * trips a false error.
 */
function skillAddress(doc, pack, e) {
    const m = String(e.name ?? '').match(/^(.*?)\s*\(([^)]*)\)\s*$/);
    const base = m ? m[1] : String(e.name ?? '');
    let speciality = m ? m[2].trim() : null;
    if (speciality && /^new speciality$/i.test(speciality)) speciality = null;  // pre-fix placeholder
    const canonical = canonicalSkillName(base)
        ?? canonicalSkillName(pack.skills?.find((s) => s.ref === e.ref)?.name ?? '');
    if (!canonical) return null;
    const entry = skillEntryFor(doc, canonical);
    if (!SKILL_DEFS[canonical].specialist) return { label: canonical, got: entry?.advances ?? 0 };
    const specs = entry?.specialities ?? {};
    if (speciality) {
        const key = Object.keys(specs).find((k) => norm(k) === norm(speciality));
        return { label: `${canonical} (${speciality})`, got: (key ? specs[key]?.advances : 0) ?? 0 };
    }
    return { label: canonical, got: Math.max(0, ...Object.values(specs).map((v) => v?.advances ?? 0)) };
}

/**
 * Every talent name the document's RECORDED origin grants (finding D-12).
 * Background talent grants, role talent choices (every option — the document
 * does not record which was picked) and elite advances, each normalised and
 * also stored without its "(X)" so "Weapon Training (Las)" matches the grant
 * "Weapon Training (Flame or Las, Chain)". Origin members are matched by ref
 * first, then by name (v3→v4 migrated documents carry names only).
 */
/**
 * Expand a grant's alternatives into one name each.
 *
 * DH2 writes a choice inside the parenthetical — "Weapon Training (Flame or
 * Las, Chain)" means Weapon Training in ONE of Flame, Las or Chain — so the
 * alternation belongs to the specialisation, not to the talent name. Splitting
 * the whole string on " or " produced ["weapon training (flame", "las, chain)"],
 * neither of which is a talent; only the parenthetical-stripping fallback made
 * grant matching work at all.
 *
 * Input is already normalised (lowercased) by the caller.
 */
function expandAlternatives(name) {
    const m = name.match(/^(.*?)\s*\((.*)\)\s*$/);
    if (!m) {
        // No parenthetical: a bare "Hardy or Resistance" is a genuine choice
        // between two whole talents.
        return name.split(' or ').map((s) => s.trim()).filter(Boolean);
    }
    const [, base, inner] = m;
    const options = inner
        .split(/\s+or\s+|,/)          // "Flame or Las, Chain" -> Flame | Las | Chain
        .map((s) => s.trim())
        .filter(Boolean);
    if (!options.length) return [name];
    return options.map((o) => `${base} (${o})`);
}


function originGrantedTalents(doc, pack) {
    const granted = new Set();
    const add = (n) => {
        for (const a of expandAlternatives(norm(n))) {
            if (!a) continue;
            granted.add(a);
            granted.add(a.replace(/\s*\(.*$/, ''));       // base name, parenthetical dropped
        }
    };
    const lookup = (list, member) => {
        if (!member) return null;
        const ref = member.ref, name = norm(entryName(member));
        return list.find((x) => (ref && x.ref === ref) || (name && norm(x.name) === name));
    };
    for (const g of lookup(pack.backgrounds, doc.origin?.background)?.talentsGranted ?? []) add(g);
    for (const g of lookup(pack.roles, doc.origin?.role)?.roleTalentChoice ?? []) add(g);
    for (const e of doc.origin?.eliteAdvances ?? []) add(entryName(e));
    return granted;
}

/**
 * Ledger ↔ counts reconciliation (decision D-I). Replays typed ledger entries
 * and compares against stored advance counts / held talents. Docs whose
 * ledger is FULLY typed (every entry has a known `kind`) must reconcile
 * exactly → mismatches are ERRORS; docs with any untyped entries are legacy →
 * mismatches are WARNINGS. Overspend (spent > total) is always an error.
 */
export function validateBuild(doc, pack) {
    const errors = [], warnings = [];
    const ledger = doc.xp?.ledger ?? [];
    const fullyTyped = ledger.length > 0 && ledger.every((e) => LEDGER_KINDS.includes(e.kind));
    const report = (msg) => (fullyTyped ? errors : warnings).push(msg);

    const { total, spent, remaining } = xpSummary(doc);
    if (remaining < 0) errors.push(`overspent: ledger total ${spent} exceeds earned XP ${total}`);

    // replay typed characteristic/skill purchases into expected counts
    const expChar = {}, expSkill = new Map();
    for (const e of ledger) {
        if (e.kind === 'characteristic' && e.ref) {
            const key = docCharKey(e.ref);               // D-1: legacy "wil" refs reconcile against "wp"
            expChar[key] = Math.max(expChar[key] ?? 0, e.rank ?? ((expChar[key] ?? 0) + 1));
        }
        if (e.kind === 'skill' && e.ref) {
            // D-3: address the doc slot the purchase wrote — canonical skill
            // name (+ speciality). Entries we cannot resolve to a DH2 skill are
            // skipped rather than guessed: a false error is worse than silence.
            const addr = skillAddress(doc, pack, e);
            if (!addr) continue;
            const prev = expSkill.get(addr.label)?.exp ?? 0;
            expSkill.set(addr.label, { got: addr.got, exp: Math.max(prev, e.rank ?? (prev + 1)) });
        }
    }
    for (const [key, exp] of Object.entries(expChar)) {
        const got = doc.characteristics?.[key]?.advances ?? 0;
        if (got !== exp) report(`characteristic ${key}: ledger implies ${exp} advances, doc has ${got}`);
    }
    for (const [label, { got, exp }] of expSkill) {
        if (got !== exp) report(`skill ${label}: ledger implies ${exp} advances, doc has ${got}`);
    }
    // talents bought must be held
    for (const e of ledger) {
        if (e.kind !== 'talent') continue;
        const held = (doc.talents ?? []).some((t) => norm(entryName(t)) === norm(e.name));
        if (!held) report(`ledger buys talent "${e.name}" but the doc does not hold it`);
    }
    // held talents with a corpus entry should have a purchase OR an origin grant
    const granted = originGrantedTalents(doc, pack);            // D-12: the escape, now implemented
    const bought = new Set(ledger.filter((e) => e.kind === 'talent').map((e) => norm(e.name)));
    for (const t of doc.talents ?? []) {
        const name = norm(entryName(t));
        const base = name.replace(/\s*\(.*\)$/, '');
        const inPack = pack.talents.some((p) => norm(p.name) === base);
        if (inPack && !bought.has(name) && !granted.has(name) && !granted.has(base) && ledger.length) {
            // ALWAYS a warning, never an error, even on a fully-typed ledger
            // (finding D-12's `fullyTyped ? warnings : warnings`): background
            // and role talent grants are applied by applyOrigin without any
            // per-talent provenance on the document, and imported characters
            // have no ledger for their pre-import history. Promoting this to an
            // error would fail ordinary builder-made characters.
            warnings.push(`talent "${entryName(t)}" held without a ledger purchase (origin grant or import)`);
        }
    }

    return { ok: errors.length === 0, errors, warnings };
}


/** Test seam for originGrantedTalents — see api/test/minor-findings.test.mjs.
 *  Exported rather than made public because the grant-expansion rules are
 *  fiddly enough to deserve direct tests, not only end-to-end ones. */
export const originGrantedTalentsForTest = originGrantedTalents;

/* ═══════════════════════════════════════════════════════════════════════════
 * Creation-flow validation + ledger replay (2026-08-27) — the engine half of
 * the Builder's integrated creation panels.
 * ═══════════════════════════════════════════════════════════════════════════ */

const originEntryFor = (pack, list, member) => {
    if (!member) return null;
    const ref = typeof member === 'object' ? member.ref : null;
    const name = norm(entryName(member));
    return pack[list].find((e) => (ref && e.ref === ref) || norm(e.name) === name) ?? null;
};

const orChoiceSatisfied = (options, satisfied) =>
    options.split(/\s+or\s+/i).some((o) => satisfied(o.trim()));

/**
 * Findings over the CHARACTER CREATION process — unselected origin members,
 * unresolved "A or B" choice points, ungenerated characteristics (with the
 * RAW 27–45 range check when the recorded method is 'raw'), unset wounds/
 * fate/influence, fate below the home-world threshold, empty divination, and
 * the Psyker↔Untouchable combination. Pure display facts: `validateBuild`
 * carries them as `creation` and the D-I errors/warnings policy is untouched.
 */
export function validateCreation(doc, pack) {
    const findings = [];
    const origin = doc.origin ?? {};
    const hw = originEntryFor(pack, 'homeworlds', origin.homeworld);
    const bg = originEntryFor(pack, 'backgrounds', origin.background);
    const role = originEntryFor(pack, 'roles', origin.role);

    for (const [member, entry, label] of [
        [origin.homeworld, hw, 'home world'], [origin.background, bg, 'background'], [origin.role, role, 'role'],
    ]) {
        if (!member) findings.push(`${label} not selected`);
        else if (!entry) findings.push(`${label} "${entryName(member)}" is not a pack entry`);
    }

    const talentHeld = (name) => (doc.talents ?? []).some((t) => norm(entryName(t)) === norm(name));
    const aptitudeHeld = (name) => (doc.aptitudes ?? []).some((a) => norm(entryName(a)) === norm(name));
    const skillTrained = (grant) => {
        const m = grant.match(/^([^(]+?)\s*\(([^)]+)\)\s*$/);
        const canonical = canonicalSkillName(m ? m[1] : grant);
        if (!canonical) return false;
        const s = skillEntryFor(doc, canonical);
        if (!s) return false;
        if (m) return (s.specialities?.[m[2]]?.advances ?? 0) >= 1;
        return (s.advances ?? 0) >= 1;
    };

    if (role?.roleTalentChoice?.length && !role.roleTalentChoice.some(talentHeld)) {
        findings.push(`role talent choice unresolved: ${role.roleTalentChoice.join(' or ')}`);
    }
    for (const [entry, kind] of [[hw?.aptitude, 'home world aptitude'], [bg?.startingAptitude, 'background aptitude']]) {
        if (entry && /\s+or\s+/i.test(entry) && !orChoiceSatisfied(entry, aptitudeHeld)) {
            findings.push(`${kind} choice unresolved: ${entry}`);
        }
    }
    for (const grant of bg?.skillsGranted ?? []) {
        if (/\s+or\s+/i.test(grant) && !orChoiceSatisfied(grant, skillTrained)) {
            findings.push(`background skill choice unresolved: ${grant}`);
        }
    }
    for (const grant of bg?.talentsGranted ?? []) {
        if (/\s+or\s+/i.test(grant) && !orChoiceSatisfied(grant, talentHeld)) {
            findings.push(`background talent choice unresolved: ${grant}`);
        }
    }

    // characteristics: generated, and RAW-legal when the recipe says rolled
    const method = doc.extensions?.builder?.creation?.characteristics?.method
        ?? doc.extensions?.builder?.wizard?.characteristics?.method ?? null;
    const CHAR_KEYS = ['ws', 'bs', 's', 't', 'ag', 'int', 'per', 'wp', 'fel'];
    const ungenerated = CHAR_KEYS.filter((k) => {
        const c = doc.characteristics?.[k];
        return !((typeof c === 'number' ? c : c?.base) > 0);
    });
    if (ungenerated.length) findings.push(`characteristics not yet generated: ${ungenerated.join(', ')}`);
    else if (method === 'raw') {
        for (const k of CHAR_KEYS) {
            const base = doc.characteristics[k].base ?? doc.characteristics[k];
            if (base < 27 || base > 45) findings.push(`characteristic ${k} value ${base} is outside the RAW 27–45 range`);
        }
    }
    if (hw && !(doc.influence > 0)) findings.push('influence not generated');

    if (!(doc.wounds?.max > 0)) findings.push('wounds not rolled/set');
    if (!(doc.fate?.max > 0)) findings.push('fate not set');
    else if (hw && doc.fate.max < hw.fateThreshold) {
        findings.push(`fate max ${doc.fate.max} is below the ${hw.name} threshold ${hw.fateThreshold}`);
    }
    if (!doc.tarot?.card && !doc.tarot?.text && !doc.tarot?.effect) findings.push('divination not recorded');

    const eas = new Set((doc.origin?.eliteAdvances ?? []).map((e) => norm(entryName(e))));
    if (eas.has('psyker') && eas.has('untouchable')) {
        findings.push('invalid combination: the Psyker and Untouchable elite advances are mutually exclusive');
    }
    return findings;
}

/**
 * Re-buy a ledger against a (possibly re-derived) doc at CURRENT prices — the
 * propagation mechanism when an earlier creation step changes. Purchases are
 * replayed in order through applyAdvance (aptitude matches and costs
 * recomputed; prerequisite failures are kept but reported), grants through
 * applyGrant via their recorded grantKind, and elite-advance grant ECHOES are
 * skipped (the EA purchase regenerates them). Anything unappliable lands in
 * `conflicts` instead of aborting the rebuild or being silently charged.
 * @returns {{ doc: object, conflicts: string[] }}
 */
export function replayPurchases(doc, pack, entries) {
    let d = structuredClone(doc);
    const conflicts = [];
    for (const e of entries ?? []) {
        try {
            if ((e.cost ?? 0) === 0 && /^Elite Advance: /.test(e.source ?? '')) continue;
            if ((e.cost ?? 0) === 0 && e.kind !== 'elite_advance') {
                const grantKind = e.grantKind
                    ?? (['talent', 'skill', 'psy_rating'].includes(e.kind) ? e.kind : 'note');
                const grant = grantKind === 'note'
                    ? { kind: 'note', text: e.name }
                    : {
                        kind: grantKind, name: e.name.replace(/\s*\([^)]*\)\s*$/, grantKind === 'skill' && e.speciality ? '' : '$&').trim(),
                        ...(e.ref && { ref: e.ref }), ...(e.rank !== undefined && { rank: e.rank }),
                        ...(grantKind === 'psy_rating' && { rating: e.rank ?? 1 }),
                        ...(e.speciality && { speciality: e.speciality }),
                    };
                if (grant.kind === 'skill') grant.name = String(e.name).replace(/\s*\([^)]*\)\s*$/, '');
                ({ doc: d } = applyGrant(d, pack, grant, { source: e.source ?? 'grant' }));
                continue;
            }
            const advance = reconstructAdvance(d, pack, e);
            if (!advance) {
                // not in the pack (custom content): carry the record verbatim
                if (e.kind === 'talent' && !(d.talents ?? []).some((t) => norm(entryName(t)) === norm(e.name))) {
                    (d.talents ??= []).push({ name: e.name, ...(e.ref && { ref: e.ref }) });
                }
                (d.xp.ledger ??= []).push({ ...e });
                continue;
            }
            if (advance.prereqsMet === false) {
                conflicts.push(`"${e.name}" now fails prerequisites (${advance.prereqProblems.join('; ')}) — kept as bought`);
            }
            ({ doc: d } = applyAdvance(d, pack, advance, { confirmed: true, source: e.source }));
        } catch (err) {
            conflicts.push(`"${e.name}" could not be re-applied: ${err.message}`);
        }
    }
    return { doc: d, conflicts };
}

/** The current-price advance object for a recorded ledger entry, or null when
 *  the pack does not know the purchase (custom content). */
function reconstructAdvance(doc, pack, e) {
    switch (e.kind) {
        case 'characteristic': {
            const packKey = Object.keys(pack.characteristicAptitudes)
                .find((pk) => docCharKey(pk) === docCharKey(e.ref));
            if (!packKey) return null;
            const matches = aptitudeMatches(doc, pack.characteristicAptitudes[packKey]);
            return {
                kind: 'characteristic', ref: docCharKey(e.ref), name: e.name, rank: e.rank, matches,
                cost: advanceCost(pack, { kind: 'characteristic', matches, rank: e.rank }),
                prereqsMet: true, prereqProblems: [],
            };
        }
        case 'skill': {
            const skill = pack.skills.find((s) => s.ref === e.ref);
            if (!skill) return null;
            const matches = aptitudeMatches(doc, skill.aptitudes);
            const m = String(e.name).match(/\(([^)]+)\)\s*$/);
            return {
                kind: 'skill', ref: e.ref, name: e.name, rank: e.rank, matches,
                speciality: skill.specialist ? (e.speciality ?? m?.[1] ?? null) : undefined,
                cost: advanceCost(pack, { kind: 'skill', matches, rank: e.rank }),
                prereqsMet: true, prereqProblems: [],
            };
        }
        case 'talent': {
            const talent = pack.talents.find((t) => t.ref === e.ref)
                ?? pack.talents.find((t) => norm(t.name) === norm(String(e.name).replace(/\s*\(.*\)$/, '')));
            if (!talent) return null;
            const matches = aptitudeMatches(doc, talent.aptitudes);
            const { met, problems } = checkPrerequisites(doc, talent.prerequisites);
            return {
                kind: 'talent', ref: talent.ref, name: e.name, tier: talent.tier, matches,
                cost: advanceCost(pack, { kind: 'talent', matches, tier: talent.tier }),
                prereqsMet: met, prereqProblems: problems,
            };
        }
        case 'psy_rating':
            return {
                kind: 'psy_rating', ref: 'psy.rating', name: e.name, rank: e.rank, matches: 0,
                cost: advanceCost(pack, { kind: 'psy_rating', rank: e.rank }),
                prereqsMet: true, prereqProblems: [],
            };
        case 'elite_advance': {
            const ea = pack.eliteAdvances.find((x) => x.ref === e.ref);
            if (!ea) return null;
            const { met, problems } = checkPrerequisites(doc,
                typeof ea.prerequisites === 'string' ? [ea.prerequisites] : ea.prerequisites);
            return {
                kind: 'elite_advance', ref: ea.ref, name: ea.name, matches: 0, cost: ea.xpCost,
                prereqsMet: met, prereqProblems: problems,
            };
        }
        default:
            return null;
    }
}
