/**
 * Coverage for the build / CLI scripts — LOC that no test loaded before this
 * file:
 *
 *   scripts/build-static.mjs      scripts/build-engine-lib.mjs
 *   scripts/serve-static.mjs      tools/sync-chargen.mjs
 *   tools/migrate-dsl.mjs         tools/import-character.mjs
 *
 * (The Foundry module lane — build-foundry, export-packs, deploy-foundry and
 * foundry/dh2-roll-vm — was retired 2026-08-25 per the workspace's OD-1
 * ruling; its test blocks left with it. Git history is the undo.)
 *
 * ── How the scripts are exercised safely ────────────────────────────────────
 * Each script takes its OUTPUT ROOT from the environment, the same way they
 * already took CORPUS_DIR: DH2_DOCS_DIR, DH2_DIST_DIR, DH2_CHARGEN_DIR. This
 * file points those at a `mkdtempSync`
 * sandbox, so a real build runs unmodified and simply writes somewhere else.
 *
 * These scripts used to write to HARDCODED paths derived from their own
 * __dirname, and this file compensated by rewriting every path underneath them
 * through a `module.registerHooks()` resolve hook. That made the tests pass
 * while leaving the scripts themselves un-configurable — nothing outside this
 * file could run a build anywhere but its one hardcoded destination. The
 * overrides fix the scripts; the redirect is gone.
 *
 * A thin `fs` shim remains, but only as a WRITE GUARD: a write path not under
 * the sandbox, os.tmpdir() or the scripts' own gitignored `.build/` scratch
 * throws instead of touching the repo. (It earns its keep — it caught a wrong
 * assumption while these overrides were being added.) The `http` shim keeps
 * serve-static from binding a real port.
 *
 * Because the real file URL is what gets imported, `--experimental-test-
 * coverage` attributes the executed lines to the real script.
 *
 * `.build/` is the one repo path the builds are allowed to touch (gitignored,
 * regenerated by every build); it is backed up and byte-restored in after().
 */
import test, { after } from 'node:test';
import assert from 'node:assert/strict';
import { registerHooks } from 'node:module';
import {
    mkdtempSync, mkdirSync, writeFileSync, readFileSync, readdirSync, rmSync,
    existsSync, statSync, cpSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { createHash } from 'node:crypto';
import { join, dirname, resolve, sep } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

import { CHARACTER_SCHEMA_VERSION, emptyCharacter } from '../lib/character-schema.mjs';
import { compile, programInfo } from '../lib/dsl/compiler.mjs';
import { migrateDsl } from '../../tools/migrate-dsl.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(HERE, '..', '..');
const TMPROOT = tmpdir();
const SANDBOX = mkdtempSync(join(TMPROOT, 'dh2-scripts-cov-'));
const scratch = (name) => {
    const d = join(SANDBOX, name);
    mkdirSync(d, { recursive: true });
    return d;
};

// ── output redirection (env) + write-guard (shim) ───────────────────────────
// The scripts now take their output roots from the environment, the same way
// they already took CORPUS_DIR. Pointing those at the sandbox
// is what keeps a real build off the repo — no path rewriting required.
//
// This replaces a resolve-hook redirect that rewrote every REPO/<zone> path
// underneath the scripts. That redirect made the tests pass while the scripts
// themselves remained un-configurable: nothing outside this file could run a
// build anywhere but its hardcoded destination.
process.env.DH2_DOCS_DIR = join(SANDBOX, 'docs');
process.env.DH2_DIST_DIR = join(SANDBOX, 'dist');
process.env.DH2_CHARGEN_DIR = join(SANDBOX, 'api', 'data', 'chargen');


const BUILD_SCRATCH = join(REPO, '.build');
const writeAllowed = (p) =>
    typeof p !== 'string'
    || p.startsWith(SANDBOX + sep) || p === SANDBOX
    || p.startsWith(TMPROOT + sep)
    || p === BUILD_SCRATCH || p.startsWith(BUILD_SCRATCH + sep);

// The shim no longer rewrites paths — it only GUARDS writes. A resolved write
// outside the sandbox, os.tmpdir() or the gitignored .build/ scratch throws
// instead of touching the repo. (This is not belt-and-braces: it caught a wrong
// assumption while these overrides were being added — that the then-extant
// export-packs script's own packs-src/ was a read root, when it in fact
// generated it.)
const FS_STATE = {
    /** every blocked write attempt lands here (asserted to stay empty) */
    blocked: [],
    w(p) {
        if (!writeAllowed(p)) {
            this.blocked.push(p);
            throw new Error(`scripts-coverage: BLOCKED write outside the sandbox: ${p}`);
        }
        return p;
    },
};
globalThis.__DH2_TEST_FS = FS_STATE;

// ── module shims (data: URLs — they may only import node: builtins and
//    absolute URLs, so the real esbuild / fvtt-cli entries are baked in) ─────
const dataUrl = (src) => 'data:text/javascript,' + encodeURIComponent(src);
const H = 'globalThis.__DH2_TEST_FS';

const fsShim = dataUrl(`
import * as R from 'node:fs';
export * from 'node:fs';
export const writeFileSync = (p, ...a) => R.writeFileSync(${H}.w(p), ...a);
export const mkdirSync = (p, ...a) => R.mkdirSync(${H}.w(p), ...a);
export const rmSync = (p, ...a) => R.rmSync(${H}.w(p), ...a);
export const copyFileSync = (s, d, ...a) => R.copyFileSync(s, ${H}.w(d), ...a);
export const cpSync = (s, d, ...a) => R.cpSync(s, ${H}.w(d), ...a);
`);

const esbuildShim = dataUrl(`
import E from ${JSON.stringify(import.meta.resolve('esbuild'))};
export const build = (o) => E.build({
    ...o,
    ...(o.outfile ? { outfile: ${H}.w(o.outfile) } : {}),
    ...(o.outdir ? { outdir: ${H}.w(o.outdir) } : {}),
});
`);

const HTTP_STATE = { handler: null, port: null, listening: false };
globalThis.__DH2_TEST_HTTP = HTTP_STATE;
const httpShim = dataUrl(`
const S = globalThis.__DH2_TEST_HTTP;
export const createServer = (handler) => {
    S.handler = handler;
    return { listen(port, cb) { S.port = port; S.listening = true; if (cb) cb(); return this; } };
};
export default { createServer };
`);

/** parent-module substring → { specifier: shimUrl } */
const SHIMS = [
    ['/scripts/build-static.mjs', { fs: fsShim, 'node:fs': fsShim, esbuild: esbuildShim }],
    ['/scripts/build-engine-lib.mjs', { fs: fsShim, 'node:fs': fsShim, esbuild: esbuildShim }],
    ['/scripts/serve-static.mjs', { http: httpShim, 'node:http': httpShim }],
    ['/tools/sync-chargen.mjs', { fs: fsShim, 'node:fs': fsShim }],
];
registerHooks({
    resolve(spec, ctx, next) {
        const parent = ctx.parentURL ?? '';
        for (const [needle, map] of SHIMS) {
            if (parent.includes(needle) && map[spec]) return { url: map[spec], shortCircuit: true };
        }
        return next(spec, ctx);
    },
});

// ── .build/ backup (the one repo dir the builds legitimately write) ─────────
const BUILD_BACKUP = join(SANDBOX, '__build_backup');
if (existsSync(BUILD_SCRATCH)) cpSync(BUILD_SCRATCH, BUILD_BACKUP, { recursive: true });

// ── real-artifact fingerprints (asserted unchanged at the end) ──────────────
const sha = (p) => createHash('sha256').update(readFileSync(p)).digest('hex');
const treeFingerprint = (dir) => {
    if (!existsSync(dir)) return 'ABSENT';
    const walk = (d) => readdirSync(d, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))
        .map((e) => (e.isDirectory() ? `${e.name}/[${walk(join(d, e.name))}]` : `${e.name}:${sha(join(d, e.name))}`))
        .join(',');
    return walk(dir);
};
const REAL_ARTIFACTS = {
    'docs/': () => treeFingerprint(join(REPO, 'docs')),
    'dist/': () => treeFingerprint(join(REPO, 'dist')),
    'api/data/chargen/pack.mjs': () => sha(join(REPO, 'api', 'data', 'chargen', 'pack.mjs')),
};
const ARTIFACTS_BEFORE = Object.fromEntries(Object.entries(REAL_ARTIFACTS).map(([k, f]) => [k, f()]));

const ENV_BACKUP = { ...process.env };

after(() => {
    if (existsSync(BUILD_BACKUP)) {
        rmSync(BUILD_SCRATCH, { recursive: true, force: true });
        cpSync(BUILD_BACKUP, BUILD_SCRATCH, { recursive: true });
    }
    for (const k of ['CORPUS_DIR', 'PORT', 'DH2_DOCS_DIR',
        'DH2_DIST_DIR', 'DH2_CHARGEN_DIR']) {
        if (k in ENV_BACKUP) process.env[k] = ENV_BACKUP[k]; else delete process.env[k];
    }
    rmSync(SANDBOX, { recursive: true, force: true });
});

// ── small helpers ───────────────────────────────────────────────────────────
const importScript = (rel, tag) =>
    import(pathToFileURL(join(REPO, rel)).href + (tag ? `?case=${tag}` : ''));

/** Run `fn` with console.{log,error,warn} and process.stdout.write captured. */
async function capture(fn, { stdout = false } = {}) {
    const out = [], err = [];
    const orig = { log: console.log, error: console.error, warn: console.warn };
    const origWrite = process.stdout.write;
    console.log = (...a) => out.push(a.map(String).join(' '));
    console.error = (...a) => err.push(a.map(String).join(' '));
    console.warn = (...a) => err.push(a.map(String).join(' '));
    if (stdout) process.stdout.write = (chunk) => { out.push(String(chunk)); return true; };
    try {
        const value = await fn();
        return { value, out, err, threw: null };
    } catch (e) {
        return { value: undefined, out, err, threw: e };
    } finally {
        console.log = orig.log; console.error = orig.error; console.warn = orig.warn;
        if (stdout) process.stdout.write = origWrite;
    }
}

/** Replace process.exit with a thrower so a CLI's exit path is observable. */
class ExitSignal extends Error {
    constructor(code) { super(`process.exit(${code})`); this.code = code; }
}
async function withExitTrap(fn) {
    const real = process.exit;
    process.exit = (code) => { throw new ExitSignal(code); };
    try { return await fn(); } finally { process.exit = real; }
}

const memo = (fn) => { let p; return () => (p ??= fn()); };

// ════════════════════════════════════════════════════════════════════════════
// scripts/build-static.mjs
// ════════════════════════════════════════════════════════════════════════════
const DOCS = join(SANDBOX, 'docs');
const runBuildStatic = memo(async () => {
    const r = await capture(() => importScript('scripts/build-static.mjs'));
    if (r.threw) throw r.threw;
    return r;
});

test('build-static: builds docs/ into the sandbox and leaves the real docs/ alone', async () => {
    const r = await runBuildStatic();
    const files = readdirSync(DOCS);
    for (const f of ['.nojekyll', 'dh2-engine.js', 'index.html', 'roll.html', 'style.css']) {
        assert.ok(files.includes(f), `docs/ should contain ${f} — got ${files.join(', ')}`);
    }
    assert.equal(treeFingerprint(join(REPO, 'docs')), ARTIFACTS_BEFORE['docs/'],
        'the REAL docs/ must be byte-identical after a sandboxed build');
    assert.match(r.out.join('\n'), /Static site built/);
});

test('build-static: every non-directory ui/ file is copied to docs/', async () => {
    await runBuildStatic();
    const uiFiles = readdirSync(join(REPO, 'ui'), { withFileTypes: true })
        .filter((e) => e.isFile()).map((e) => e.name);
    const docsFiles = new Set(readdirSync(DOCS));
    assert.ok(uiFiles.length >= 8, 'sanity: ui/ has files to copy');
    for (const f of uiFiles) assert.ok(docsFiles.has(f), `ui/${f} was not copied into docs/`);
});

test('build-static: each copied HTML gets exactly one engine tag, first in <head>', async () => {
    await runBuildStatic();
    const TAG = '<script src="dh2-engine.js"></script>';
    const htmls = readdirSync(DOCS).filter((f) => f.endsWith('.html'));
    assert.ok(htmls.length >= 4);
    for (const f of htmls) {
        const html = readFileSync(join(DOCS, f), 'utf8');
        assert.equal(html.split(TAG).length - 1, 1, `${f} should carry the engine tag exactly once`);
        const head = html.search(/<head[^>]*>/i);
        assert.ok(head >= 0, `${f} has a <head>`);
        const between = html.slice(head, html.indexOf(TAG));
        assert.ok(!/<script|<link/i.test(between.replace(/<head[^>]*>/i, '')),
            `${f}: the engine tag must precede every other head element`);
    }
});

test('build-static: dh2-engine.js is a self-contained classic IIFE with the fetch patch', async () => {
    await runBuildStatic();
    const bundle = readFileSync(join(DOCS, 'dh2-engine.js'), 'utf8');
    assert.ok(bundle.length > 200_000, `bundle looks truncated (${bundle.length} bytes)`);
    assert.match(bundle.slice(0, 200), /^\(\(\)\s*=>\s*\{/, 'iife format → the bundle opens with an IIFE');
    assert.ok(!/^\s*(export|import)\s/m.test(bundle), 'a classic script must carry no ESM syntax');
    assert.match(bundle, /fetch/, 'the bundle installs the fetch shim');
    // the DSL data is inlined (no filesystem in the browser)
    assert.match(bundle, /weapon-qualities\.dsl|Tearing|roll_table/);
});

test('build-static: emits the versioned JSON Schema artifact', async () => {
    await runBuildStatic();
    const name = `character.schema.v${CHARACTER_SCHEMA_VERSION}.json`;
    assert.ok(existsSync(join(DOCS, name)), `docs/${name} missing`);
    const schema = JSON.parse(readFileSync(join(DOCS, name), 'utf8'));
    assert.equal(typeof schema, 'object');
    assert.ok(schema.properties || schema.$defs || schema.definitions, 'looks like a JSON Schema');
});

test('build-static: writes the inlined browser twin of rules/sources.mjs', async () => {
    await runBuildStatic();
    const twin = readFileSync(join(BUILD_SCRATCH, 'sources.browser.mjs'), 'utf8');
    assert.match(twin, /AUTO-GENERATED by scripts\/build-static\.mjs/);
    for (const name of ['RULE_FILES', 'ruleSources', 'weaponsJson']) {
        assert.match(twin, new RegExp(`export const ${name} = `), `twin must export ${name}`);
    }
});

// ════════════════════════════════════════════════════════════════════════════
// scripts/build-engine-lib.mjs
// ════════════════════════════════════════════════════════════════════════════
const ENGINE_LIB = join(SANDBOX, 'dist', 'dh2-engine.mjs');
const runBuildEngineLib = memo(async () => {
    const r = await capture(() => importScript('scripts/build-engine-lib.mjs'));
    if (r.threw) throw r.threw;
    return r;
});

test('build-engine-lib: emits dist/dh2-engine.mjs and the generated library entry', async () => {
    const r = await runBuildEngineLib();
    assert.ok(existsSync(ENGINE_LIB));
    assert.equal(treeFingerprint(join(REPO, 'dist')), ARTIFACTS_BEFORE['dist/'],
        'the REAL dist/ must be untouched');
    const entry = readFileSync(join(BUILD_SCRATCH, 'engine-lib-entry.mjs'), 'utf8');
    assert.match(entry, /export \{ dispatch \} from/);
    assert.match(entry, /export const ENGINE_LIB_VERSION = /);
    const version = JSON.parse(readFileSync(join(REPO, 'package.json'), 'utf8')).version;
    assert.match(r.out.join('\n'), new RegExp(`Engine library built.*v${version.replace(/\./g, '\\.')}`));
});

test('build-engine-lib: the bundle exposes exactly the documented host surface', async () => {
    await runBuildEngineLib();
    const lib = await import(pathToFileURL(ENGINE_LIB).href);
    const expected = [
        'dispatch', 'CHARACTER_SCHEMA_VERSION', 'CHARACTER_FIELDS', 'LEDGER_KINDS',
        'migrateCharacter', 'validateCharacter', 'emptyCharacter',
        'characterToCombatant', 'characteristicTotal', 'characteristicBonus', 'skillTarget',
        'ENGINE_LIB_VERSION',
    ];
    assert.deepEqual([...Object.keys(lib)].sort(), [...expected].sort());
    assert.equal(lib.ENGINE_LIB_VERSION,
        JSON.parse(readFileSync(join(REPO, 'package.json'), 'utf8')).version);
    assert.equal(lib.CHARACTER_SCHEMA_VERSION, CHARACTER_SCHEMA_VERSION);
});

test('build-engine-lib: dispatch works through the bundled seam (stateless, no globals)', async () => {
    await runBuildEngineLib();
    const lib = await import(pathToFileURL(ENGINE_LIB).href);
    const weapons = lib.dispatch('GET', '/api/weapons');
    assert.equal(weapons.status, 200);
    assert.ok(Array.isArray(weapons.body.weapons) && weapons.body.weapons.length > 0);
    assert.equal(lib.dispatch('GET', '/api/does-not-exist').status, 404);
    assert.equal(lib.dispatch('DELETE', '/api/weapons').status, 405);
    const doc = lib.emptyCharacter('Bundled');
    assert.equal(lib.validateCharacter(doc).ok, true);
});

// ════════════════════════════════════════════════════════════════════════════
// scripts/serve-static.mjs — no port is ever bound
// ════════════════════════════════════════════════════════════════════════════
// Importing this module no longer binds a port (it used to .listen() at module
// scope, so the handler was reachable only by intercepting http.createServer,
// and a plain import hung). Take the exported handler, and call main()
// explicitly to cover the listen path.
let SERVE_HANDLER = null;
const runServeStatic = memo(async () => {
    await runBuildStatic();                       // docsDir is redirected to SANDBOX/docs
    mkdirSync(join(DOCS, 'sub'), { recursive: true });
    writeFileSync(join(DOCS, 'sub', 'index.html'), '<html>sub</html>');
    process.env.PORT = '61999';
    const r = await capture(async () => {
        const mod = await importScript('scripts/serve-static.mjs');
        SERVE_HANDLER = mod.handler;
        mod.main();                               // the shimmed createServer records port + handler
    });
    if (r.threw) throw r.threw;
    return r;
});
/** drive the captured request handler with a fake req/res pair */
async function request(url) {
    const res = { status: null, headers: null, body: null };
    let done;
    const p = new Promise((r) => { done = r; });
    await SERVE_HANDLER({ url }, {
        writeHead(status, headers) { res.status = status; res.headers = headers; },
        end(data) { res.body = data; done(); },
    });
    await p;
    return { ...res, type: res.headers?.['Content-Type'] };
}

test('serve-static: creates a server and listens on $PORT without binding in tests', async () => {
    const r = await runServeStatic();
    assert.equal(typeof SERVE_HANDLER, 'function', 'the handler is a named export, not a hidden callback');
    assert.equal(HTTP_STATE.handler, SERVE_HANDLER, 'main() passes that same handler to createServer');
    assert.equal(HTTP_STATE.port, '61999', 'PORT env must win over the 8080 default');
    assert.match(r.out.join('\n'), /Static docs\/ served at http:\/\/localhost:61999/);
});

test('serve-static: serves / as index.html with the right MIME types', async () => {
    await runServeStatic();
    const root = await request('/');
    assert.equal(root.status, 200);
    assert.equal(root.type, 'text/html; charset=utf-8');
    assert.deepEqual(root.body, readFileSync(join(DOCS, 'index.html')));

    const cases = [
        ['/style.css', 'text/css; charset=utf-8'],
        ['/char-store.js', 'text/javascript; charset=utf-8'],
        ['/builder-core.mjs', 'text/javascript; charset=utf-8'],
        [`/character.schema.v${CHARACTER_SCHEMA_VERSION}.json`, 'application/json; charset=utf-8'],
        ['/.nojekyll', 'application/octet-stream'],
    ];
    for (const [url, mime] of cases) {
        const res = await request(url);
        assert.equal(res.status, 200, `${url} should be served`);
        assert.equal(res.type, mime, `${url} MIME`);
    }
});

test('serve-static: directory requests fall through to index.html', async () => {
    await runServeStatic();
    const res = await request('/sub');
    assert.equal(res.status, 200);
    assert.equal(String(res.body), '<html>sub</html>');
});

test('serve-static: unknown paths 404 and traversal attempts cannot escape docs/', async () => {
    await runServeStatic();
    const missing = await request('/no-such-file.html');
    assert.equal(missing.status, 404);
    assert.equal(missing.type, 'text/plain');
    assert.equal(missing.body, '404 Not Found');
    // the WHATWG URL parser resolves dot segments (encoded or not) before the
    // handler sees them, so these all land inside docs/ and 404.
    for (const url of ['/../../package.json', '/%2e%2e/%2e%2e/package.json',
        '/a/%2e%2e/%2e%2e/%2e%2e/package.json', '/..%2f..%2fpackage.json']) {
        const res = await request(url);
        assert.equal(res.status, 404, `${url} must not escape docs/`);
    }
    const decoded = await request('/style%2ecss');
    assert.equal(decoded.status, 200, 'percent-decoding of ordinary names still works');
});

// ════════════════════════════════════════════════════════════════════════════
// tools/sync-chargen.mjs — never over the committed api/data/chargen/pack.mjs
// ════════════════════════════════════════════════════════════════════════════
const PACK_OUT = join(SANDBOX, 'api', 'data', 'chargen', 'pack.mjs');
function writeCorpus(dir, { duplicateTalentIds = false } = {}) {
    const w = (rel, obj) => {
        mkdirSync(dirname(join(dir, rel)), { recursive: true });
        writeFileSync(join(dir, rel), JSON.stringify(obj, null, 2));
    };
    const prov = (p) => ({ _source: `src_dh2_core_p${p}`, _book_page: p - 1 });
    w('_errata_overrides.json', {
        data_overrides: {
            talents: {
                patches: [
                    // the `_`-prefixed keys are errata metadata: they must NOT be
                    // merged onto the entry (_source in particular is provenance
                    // that the projection copies straight into the pack).
                    {
                        id: 'blademaster', aptitudes: ['Weapon Skill', 'Finesse'],
                        _errata_note: 'PROSE must not leak',
                        _source: 'src_dh2_errata_p999', _book_page: 999,
                    },
                    { id: 'no_such_talent', name: 'Ghost' },
                ],
            },
            skills: { patches: [{ id: 'awareness', characteristic: 'per' }] },
            home_worlds: {},
            backgrounds: { notpatches: [] },
        },
    });
    w('data/talents.json', {
        tier_1: [
            { id: 'blademaster', name: 'Blademaster', aptitudes: ['Weapon Skill'], prerequisites: ['WS 30'], benefit: 'PROSE benefit text', ...prov(63) },
            { id: duplicateTalentIds ? 'blademaster' : 'quick_draw', name: 'Quick Draw', ...prov(64) },
        ],
        tier_2: [{ id: 'crushing_blow', name: 'Crushing Blow', aptitudes: ['Strength', 'Offence'], specialist: true, description: 'PROSE description', ...prov(65) }],
        tier_3: [{ id: 'deathdealer', name: 'Deathdealer', prerequisites: [], ...prov(66) }],
    });
    w('data/skills.json', {
        entries: [
            { id: 'awareness', name: 'Awareness', characteristic: 'int', aptitudes: ['Perception', 'Fieldcraft'], skill_use: 'PROSE use', ...prov(97) },
            { id: 'lore_common', name: 'Common Lore', characteristic: 'int', specialist: true, alternate_characteristics: ['per'], ...prov(98) },
        ],
    });
    w('data/home_worlds.json', {
        entries: [{
            id: 'hive_world', name: 'Hive World',
            characteristic_modifiers: { ag: 3, per: 3, wp: -3 },
            fate_threshold: 9, emperors_blessing: 3,
            home_world_bonus: { name: 'Hivebound', benefit: 'PROSE bonus body' },
            home_world_aptitude: 'Social', wounds_formula: '7+1d5',
            recommended_backgrounds: ['imperial_guard'], ...prov(31),
        }],
    });
    w('data/backgrounds.json', {
        entries: [{
            id: 'imperial_guard', name: 'Imperial Guard',
            skills_granted: ['Athletics'], talents_granted: ['Nerves of Steel'],
            starting_aptitude: 'Offence', starting_equipment_class: 'guard',
            concept: 'PROSE concept', ...prov(43),
        }],
    });
    w('data/roles.json', {
        entries: [{
            id: 'assassin', name: 'Assassin',
            role_aptitudes: ['Fellowship or Perception'], role_talent_choice: ['Sprint'],
            role_bonus: { name: 'Rapid Takedown', benefit: 'PROSE role body' }, ...prov(70),
        }],
    });
    w('data/traits.json', { entries: [{ id: 'unnatural_strength', name: 'Unnatural Strength', rated: true, description: 'PROSE trait', ...prov(140) }] });
    w('data/elite_advances.json', { entries: [{ id: 'psyker', name: 'Psyker', xp_cost: 1000, prerequisites: ['WP 40'], ...prov(90) }] });
    w('data/advancement.json', {
        starting_xp: { value: 1000 },
        aptitudes: { entries: [{ id: 'general', name: 'General', kind: 'named', _source: 'x' }] },
        characteristic_aptitudes: { ws: { aptitudes: ['Weapon Skill', 'Offence'] }, _note: 'ignored' },
        characteristic_advance_costs: { ranks: ['simple'], matches_2: [100], matches_1: [250], matches_0: [500], _quote: 'x' },
        skill_advance_costs: { ranks: ['known'], matches_2: [100], matches_1: [200], matches_0: [300] },
        talent_costs: { tier_1: { matches_2: 200 }, tier_2: { matches_2: 300 }, tier_3: { matches_2: 400 } },
        psy_rating_cost: { formula: 'cost_xp = 200 * new_psy_rating' },
    });
    return dir;
}
const runSyncChargen = memo(async () => {
    process.env.CORPUS_DIR = writeCorpus(scratch('corpus-ok'));
    const r = await capture(() => importScript('tools/sync-chargen.mjs', 'ok'));
    if (r.threw) throw r.threw;
    const { CHARGEN_PACK } = await import(pathToFileURL(PACK_OUT).href);
    return { ...r, pack: CHARGEN_PACK };
});

test('sync-chargen: writes the pack to the redirected path, never the committed one', async () => {
    const r = await runSyncChargen();
    assert.ok(existsSync(PACK_OUT));
    assert.equal(sha(join(REPO, 'api', 'data', 'chargen', 'pack.mjs')),
        ARTIFACTS_BEFORE['api/data/chargen/pack.mjs'],
        'the committed api/data/chargen/pack.mjs must be byte-identical');
    assert.match(r.out.join('\n'), /4 talents, 2 skills, 1 homeworlds, 1 backgrounds, 1 roles, 1 traits, 1 elite advances, 1 aptitudes/);
    assert.match(readFileSync(PACK_OUT, 'utf8'), /GENERATED by `npm run sync:chargen`/);
});

test('sync-chargen: projects every corpus section with dh2:<type>:<id> refs', async () => {
    const { pack } = await runSyncChargen();
    assert.equal(pack.packVersion, 1);
    assert.equal(pack.startingXp, 1000);
    assert.equal(typeof pack.generatedAt, 'string');
    assert.equal(pack.corpus.system, 'dark_heresy_2e');
    assert.deepEqual(pack.talents.map((t) => t.ref),
        ['dh2:talent:blademaster', 'dh2:talent:quick_draw', 'dh2:talent:crushing_blow', 'dh2:talent:deathdealer']);
    assert.deepEqual(pack.talents.map((t) => t.tier), [1, 1, 2, 3]);
    assert.equal(pack.skills[0].ref, 'dh2:skill:awareness');
    assert.equal(pack.homeworlds[0].ref, 'dh2:home_world:hive_world');
    assert.equal(pack.backgrounds[0].ref, 'dh2:background:imperial_guard');
    assert.equal(pack.roles[0].ref, 'dh2:role:assassin');
    assert.equal(pack.traits[0].ref, 'dh2:trait:unnatural_strength');
    assert.equal(pack.eliteAdvances[0].ref, 'dh2:elite_advance:psyker');
    // name-only projections of the prose-carrying bonus blocks
    assert.equal(pack.homeworlds[0].bonusName, 'Hivebound');
    assert.equal(pack.roles[0].roleBonusName, 'Rapid Takedown');
    assert.equal(pack.traits[0].rated, true);
    assert.equal(pack.skills[1].alternateCharacteristics[0], 'per');
    assert.ok(!('alternateCharacteristics' in pack.skills[0]), 'omitted when the corpus has none');
    assert.equal(pack.eliteAdvances[0].xpCost, 1000);
    // provenance retained
    assert.equal(pack.talents[0]._source, 'src_dh2_core_p63');
    assert.equal(pack.talents[0]._book_page, 62);
});

test('sync-chargen: applies errata by id and skips underscore-prefixed patch keys', async () => {
    const { pack } = await runSyncChargen();
    const blademaster = pack.talents.find((t) => t.id === 'blademaster');
    assert.deepEqual(blademaster.aptitudes, ['Weapon Skill', 'Finesse'], 'errata patch applied');
    assert.ok(!('_errata_note' in blademaster), 'errata metadata must not leak into the pack');
    assert.equal(blademaster._source, 'src_dh2_core_p63',
        'a `_`-prefixed patch key must not overwrite the entry provenance');
    assert.equal(blademaster._book_page, 62);
    assert.equal(pack.skills[0].characteristic, 'per', 'skills errata applied');
    assert.ok(!pack.talents.some((t) => t.name === 'Ghost'), 'a patch for an unknown id is ignored');
});

test('sync-chargen: strips rulebook prose (decision D-H) from the emitted pack', async () => {
    await runSyncChargen();
    const whole = readFileSync(PACK_OUT, 'utf8');
    const text = whole.slice(whole.indexOf('export const CHARGEN_PACK'));   // skip the banner
    assert.ok(!text.includes('PROSE'), 'no prose field may survive the allowlist projections');
    for (const key of ['benefit', 'description', 'concept', 'skill_use']) {
        assert.ok(!new RegExp(`"${key}"`).test(text), `prose key "${key}" leaked into the pack`);
    }
});

test('sync-chargen: costs/aptitude tables are stripped to their numeric columns', async () => {
    const { pack } = await runSyncChargen();
    assert.deepEqual(Object.keys(pack.costs.characteristic).sort(),
        ['matches_0', 'matches_1', 'matches_2', 'ranks']);
    assert.deepEqual(pack.costs.characteristic.matches_2, [100]);
    assert.deepEqual(pack.costs.talent.tier_3, { matches_2: 400 });
    assert.equal(pack.costs.psyRating.perRating, 200);
    assert.match(pack.costs.psyRating.formula, /200 \* new_psy_rating/);
    assert.deepEqual(pack.aptitudes, [{ id: 'general', name: 'General', kind: 'named' }]);
    assert.deepEqual(pack.characteristicAptitudes, { ws: ['Weapon Skill', 'Offence'] },
        'underscore-prefixed corpus keys are filtered out');
});

test('sync-chargen: reports the corpus commit, or "unknown" outside a checkout', async () => {
    const { pack } = await runSyncChargen();
    assert.equal(typeof pack.corpus.commit, 'string');
    assert.equal(pack.corpus.commit, 'unknown', 'a temp-dir corpus is not a git checkout');
});

test('sync-chargen: duplicate slug refs fail the sync instead of silently colliding', async () => {
    process.env.CORPUS_DIR = writeCorpus(scratch('corpus-dup'), { duplicateTalentIds: true });
    const r = await capture(() => importScript('tools/sync-chargen.mjs', 'dup'));
    assert.ok(r.threw, 'a duplicate ref must throw');
    assert.match(String(r.threw.message), /duplicate ref: dh2:talent:blademaster/);
});

// ════════════════════════════════════════════════════════════════════════════
// tools/migrate-dsl.mjs
// ════════════════════════════════════════════════════════════════════════════
test('migrate-dsl: bumps the pragma and rewrites v1 alias facts to scoped paths', () => {
    const src = [
        'dsl 1',
        'quality "x" {',
        '  on TO_HIT',
        '  when target_armour > 2 and target_has_trait("Daemonic") then',
        '    set bonus += target_tb + target_sb + target_unnatural_toughness',
        '}',
    ].join('\n');
    const { text, changes } = migrateDsl(src);
    assert.match(text, /^dsl 3\n/);
    assert.match(text, /target\.armour > 2/);
    assert.match(text, /target\.has_trait\("Daemonic"\)/);
    assert.match(text, /target\.tb \+ target\.sb \+ target\.unnatural_toughness/);
    assert.ok(!/target_/.test(text), 'no prefixed alias may survive');
    assert.equal(changes, 6, 'pragma + 5 alias rewrites');
});

test('migrate-dsl: rewrites the thin sugar verbs to slot/flag primitives', () => {
    const cases = [
        ['add_die 2', 'set extra_dice += 2'],
        ['add_hits 1', 'set extra_hits += 1'],
        ['reduce_unnatural_toughness 3', 'set unnatural_toughness_reduction += 3'],
        ['keep_highest', 'flag keep_highest'],
        ['fail', 'flag attack_failed'],
        ['prevent_parry', 'flag no_parry'],
        ['cannot_parry', 'flag cannot_parry'],
        ['detonate', 'flag detonate'],
    ];
    for (const [from, to] of cases) {
        const { text, changes } = migrateDsl(`dsl 3\nquality "r" { then ${from} }`);
        assert.equal(text, `dsl 3\nquality "r" { then ${to} }`, `${from} → ${to}`);
        assert.equal(changes, 1);
    }
});

test('migrate-dsl: rewrites the v1 predicate/accessor aliases', () => {
    const { text } = migrateDsl('dsl 2\nquality "r" { when has_status("Stunned") and firing_mode == "full" and opposing_present and opposing_has_quality("Defensive") then set bonus += 1 }');
    assert.match(text, /has_condition\("Stunned"\)/);
    assert.match(text, /configuration == "full"/);
    assert.match(text, /opposing_weapon\.present/);
    assert.match(text, /opposing_weapon\.has_quality\("Defensive"\)/);
});

test('migrate-dsl: kind aliases are rewritten only where a rule can start', () => {
    const { text } = migrateDsl('dsl 3\nstatus "On Fire" { }\ngeneric "Thing" { }\nrule "Other" { }\n');
    assert.match(text, /^condition "On Fire"/m);
    assert.match(text, /^miscellaneous "Thing"/m);
    assert.match(text, /^miscellaneous "Other"/m);
    // not at a line start, and not followed by a quoted name → untouched
    const inline = migrateDsl('dsl 3\nquality "r" { when kind == status then set bonus += 1 }');
    assert.match(inline.text, /== status then/);
    assert.equal(inline.changes, 0);
});

test('migrate-dsl: comments and string literals are never rewritten', () => {
    const src = [
        'dsl 3',
        '// target_armour and add_die stay put',
        '# has_status too',
        'quality "keep target_armour" { then set note = "add_die \\" firing_mode" }',
    ].join('\n');
    const { text, changes } = migrateDsl(src);
    assert.equal(changes, 0);
    assert.equal(text, src, 'comment/string regions must round-trip byte-identical');
});

test('migrate-dsl: replacements respect word boundaries', () => {
    const { text, changes } = migrateDsl('dsl 3\nquality "r" { when failed and target_armour_extra and add_diesel then set bonus += 1 }');
    assert.equal(changes, 0);
    assert.match(text, /when failed and target_armour_extra and add_diesel/);
});

test('migrate-dsl: a file with no pragma gains `dsl 3`; an already-v3 file is a no-op', () => {
    const noPragma = migrateDsl('quality "r" { then set bonus += 1 }');
    assert.match(noPragma.text, /^dsl 3\n/);
    assert.equal(noPragma.changes, 1);

    const v3 = 'dsl 3\nquality "r" { then set bonus += 1 }\n';
    const already = migrateDsl(v3);
    assert.equal(already.changes, 0);
    assert.equal(already.text, v3);
});

test('migrate-dsl: migration is idempotent for the slot verbs and the scoped paths', () => {
    const src = 'dsl 1\nquality "r" { when target_armour > 1 then add_die 1 }';
    const once = migrateDsl(src).text;
    const twice = migrateDsl(once).text;
    assert.equal(twice, once);
    assert.equal(migrateDsl(once).changes, 0);
});

test('migrate-dsl: FIXED — the migration is idempotent for the `flag` sugar verbs', () => {
    // WAS (until 2026-07-31): `detonate` -> `flag detonate`, but the table still
    // matched the bare word inside its own output, so a second pass produced
    // `flag flag detonate`. api/data/rules/weapon-qualities.dsl:22, :506 and
    // :546 already ship those expanded forms, so
    // `node tools/migrate-dsl.mjs --all --write` corrupted the repository's own
    // rule files on the FIRST run — verified: 3 corruptions introduced.
    // NOW an expansion is skipped when `flag ` already precedes the verb.
    for (const verb of ['detonate', 'keep_highest', 'cannot_parry']) {
        const already = `dsl 3\nquality "r" { then flag ${verb} }`;
        const once = migrateDsl(already);
        assert.equal(once.text, already, `flag ${verb} must be a fixed point`);
        assert.equal(once.changes, 0, `flag ${verb} needs no migration`);
        // and the bare verb still expands exactly once
        const bare = migrateDsl(`dsl 3\nquality "r" { then ${verb} }`);
        assert.equal(bare.text, `dsl 3\nquality "r" { then flag ${verb} }`);
        assert.equal(bare.changes, 1);
        // re-running the expanded output is a no-op
        assert.equal(migrateDsl(bare.text).text, bare.text);
    }
    // the verbs that expand to `set …` are stable
    const stable = migrateDsl('dsl 3\nquality "r" { then set extra_dice += 1 }');
    assert.equal(stable.changes, 0);
});

test('migrate-dsl: migrated v1 source compiles as valid v3', () => {
    const src = [
        'dsl 1',
        'package "test.migrate" { system "dh2" source "test" }',
        'quality "Tearing" {',
        '  on DAMAGE_POOL',
        '  when has_status("Prone") and target_armour > 0',
        '  then add_die 1',
        '}',
    ].join('\n');
    const { text } = migrateDsl(src);
    assert.equal(programInfo(text).dslVersion, 3);
    assert.equal(programInfo(text).package.name, 'test.migrate');
    const effects = compile(text);
    assert.equal(effects.length, 1, 'the migrated program compiles to one effect');
});

test('migrate-dsl: FIXED — a newer DSL version is refused, not silently downgraded', () => {
    // WAS: `dsl 4` was rewritten to `dsl 3` with changes: 0, so `--write`
    // silently downgraded a newer file while reporting it had done nothing.
    // NOW it throws, and the CLI reports it and exits 1 BEFORE writing — so
    // `--all` cannot half-migrate a directory.
    assert.throws(
        () => migrateDsl('dsl 4\nquality "r" { then set bonus += 1 }'),
        /cannot migrate dsl 4 down to 3/);
    // the supported directions still work
    assert.equal(migrateDsl('dsl 3\nquality "r" { then set bonus += 1 }').changes, 0);
    assert.equal(migrateDsl('dsl 2\nquality "r" { then set bonus += 1 }').changes, 1);
});

/** The CLI's `isMain` guard compares only the BASENAME of process.argv[1] to
 *  the tail of import.meta.url, so the cache-busting query has to be part of
 *  the faked argv (see the testability findings). */
// Drive the CLI through its exported main(args).
//
// This used to set process.argv[1] = `/x/migrate-dsl.mjs?case=<tag>` and import
// the module with a cache-busting query, which "worked" only because the old
// isMain compared BASENAMES — the fake argv matched the real import URL by
// coincidence. The suite was therefore a consumer of the defect it should have
// caught, and it also defeated coverage (Node merges coverage per module URL,
// so each cache-busted re-import was discarded). main() takes the args
// directly, so no global is touched and the exit code is a return value.
const runMigrateCli = async (args, _tag) => {
    const { main } = await import('../../tools/migrate-dsl.mjs');
    let code;
    const r = await capture(() => { code = main(args); }, { stdout: true });
    return { ...r, code };
};

test('migrate-dsl CLI: prints to stdout by default and writes with --write', async () => {
    const file = join(scratch('dsl'), 'sample.dsl');
    const original = 'dsl 1\nquality "r" { when target_armour > 1 then add_die 1 }\n';
    writeFileSync(file, original);

    let r = await runMigrateCli([file], 'stdout');
    assert.equal(r.code, 0);
    assert.match(r.out.join(''), /^dsl 3\n/);
    assert.match(r.out.join(''), /target\.armour > 1 then set extra_dice \+= 1/);
    assert.equal(readFileSync(file, 'utf8'), original, 'no --write → the file is untouched');

    r = await runMigrateCli([file, '--write'], 'write');
    assert.equal(r.code, 0);
    assert.match(r.out.join('\n'), new RegExp(`${file} — 3 change\\(s\\)`));
    assert.match(readFileSync(file, 'utf8'), /^dsl 3\n/);
    assert.match(readFileSync(file, 'utf8'), /set extra_dice \+= 1/);
});

test('migrate-dsl CLI: --all reads every built-in rule file (read-only without --write)', async () => {
    const before = treeFingerprint(join(REPO, 'api', 'data', 'rules'));
    const r = await runMigrateCli(['--all'], 'all');
    assert.equal(r.code, 0, 'a read-only --all run succeeds');
    const printed = r.out.join('');
    const dslFiles = readdirSync(join(REPO, 'api', 'data', 'rules')).filter((f) => f.endsWith('.dsl'));
    assert.ok(dslFiles.length >= 8);
    assert.ok(printed.split('dsl 3\n').length - 1 >= dslFiles.length,
        'one migrated program printed per .dsl file');
    assert.equal(treeFingerprint(join(REPO, 'api', 'data', 'rules')), before,
        'without --write the rule files must be untouched');
});

test('migrate-dsl CLI: no file arguments exits 2 with usage', async () => {
    const r = await runMigrateCli([], 'usage');
    assert.equal(r.code, 2, 'usage is exit 2, and the CLI wrapper passes it to process.exit');
    assert.match(r.err.join('\n'), /usage: node tools\/migrate-dsl\.mjs/);
});

// ════════════════════════════════════════════════════════════════════════════
// tools/import-character.mjs
// ════════════════════════════════════════════════════════════════════════════
const IMPORT_DIR = scratch('import');
async function runImport(args, tag) {
    const argv = process.argv;
    process.argv = [argv[0], `/x/import-character.mjs?case=${tag}`, ...args];
    const r = await capture(() => withExitTrap(() => importScript('tools/import-character.mjs', tag)), { stdout: true });
    process.argv = argv;
    return r;
}

test('import-character: no file argument exits 2 with usage', async () => {
    const r = await runImport([], 'usage');
    assert.ok(r.threw instanceof ExitSignal);
    assert.equal(r.threw.code, 2);
    assert.match(r.err.join('\n'), /usage: node tools\/import-character\.mjs <file>/);
});

test('import-character: canonical JSON passes through, validates and prints to stdout', async () => {
    const doc = emptyCharacter('Canon Acolyte');
    const file = join(IMPORT_DIR, 'canon.json');
    writeFileSync(file, JSON.stringify(doc));
    const r = await runImport([file], 'canonical');
    assert.equal(r.threw, null, r.threw?.stack);
    const printed = JSON.parse(r.out.join(''));
    assert.equal(printed.name, 'Canon Acolyte');
    assert.equal(printed.schemaVersion, CHARACTER_SCHEMA_VERSION);
});

test('import-character: --out writes the file and stamps source.importedAt', async () => {
    const doc = emptyCharacter('Stamped');
    doc.source = { adapter: 'test', importedAt: null };
    const file = join(IMPORT_DIR, 'stamped.json');
    const out = join(IMPORT_DIR, 'stamped.out.json');
    writeFileSync(file, JSON.stringify(doc));
    const r = await runImport([file, `--out=${out}`], 'out');
    assert.equal(r.threw, null, r.threw?.stack);
    const written = JSON.parse(readFileSync(out, 'utf8'));
    assert.equal(written.name, 'Stamped');
    assert.match(written.source.importedAt, /^\d{4}-\d{2}-\d{2}T/);
    assert.match(r.err.join('\n'), /✓ valid .* "Stamped" → /);
    assert.equal(r.out.join(''), '', '--out suppresses the stdout dump');
});

test('import-character: auto-detects a Roll20 attribute dump and reports unmapped attributes', async () => {
    const file = join(IMPORT_DIR, 'roll20.json');
    writeFileSync(file, JSON.stringify({
        name: 'Roll20 Acolyte',
        attribs: [
            { name: 'WeaponSkill', current: '38' },
            { name: 'BallisticSkill', current: '33' },
            { name: 'MaxWounds', current: '12' },
            { name: 'ThisIsNotASheetAttribute', current: '1' },
        ],
    }));
    const out = join(IMPORT_DIR, 'roll20.out.json');
    const r = await runImport([file, `--out=${out}`], 'roll20');
    assert.equal(r.threw, null, r.threw?.stack);
    const written = JSON.parse(readFileSync(out, 'utf8'));
    assert.equal(written.name, 'Roll20 Acolyte');
    assert.deepEqual(written.characteristics.ws, { base: 38, advances: 0, modifiers: [] });
    assert.equal(written.wounds.max, 12);
    assert.match(r.err.join('\n'), /note: unmapped Roll20 attributes: .*ThisIsNotASheetAttribute/);
});

test('import-character: a .csv is routed to the Google-Sheets adapter and unknown keys are reported', async () => {
    const file = join(IMPORT_DIR, 'sheet.csv');
    writeFileSync(file, ['name,CSV Acolyte', 'ws,41', 'bs,30', 'wounds max,11', 'no such key,7'].join('\n'));
    const out = join(IMPORT_DIR, 'sheet.out.json');
    const r = await runImport([file, `--out=${out}`], 'csv');
    assert.equal(r.threw, null, r.threw?.stack);
    const written = JSON.parse(readFileSync(out, 'utf8'));
    assert.equal(written.name, 'CSV Acolyte');
    assert.deepEqual(written.characteristics.ws, { base: 41, advances: 0, modifiers: [] });
    assert.equal(written.wounds.max, 11);
    assert.match(r.err.join('\n'), /note: unknown template keys ignored: no such key/);
});

test('import-character: an explicit --adapter overrides auto-detection', async () => {
    const file = join(IMPORT_DIR, 'explicit.json');
    writeFileSync(file, JSON.stringify({ name: 'Explicit', attribs: [{ name: 'Toughness', current: '40' }] }));
    const r = await runImport([file, '--adapter=roll20'], 'explicit');
    assert.equal(r.threw, null, r.threw?.stack);
    assert.equal(JSON.parse(r.out.join('')).name, 'Explicit');
});

test('import-character: validation errors are printed per field and exit 1', async () => {
    const doc = emptyCharacter('Broken');
    doc.characteristics.ws.base = 'not-a-number';
    doc.wounds.max = -5;
    const file = join(IMPORT_DIR, 'broken.json');
    writeFileSync(file, JSON.stringify(doc));
    const r = await runImport([file], 'invalid');
    assert.ok(r.threw instanceof ExitSignal, 'invalid input must exit non-zero');
    assert.equal(r.threw.code, 1);
    const err = r.err.join('\n');
    assert.match(err, /^ERROR: /m);
    assert.match(err, /validation error\(s\) — fix the source and re-run/);
});

// ════════════════════════════════════════════════════════════════════════════
// global safety net
// ════════════════════════════════════════════════════════════════════════════
test('SAFETY: no script wrote outside the sandbox and every real artifact is unchanged', () => {
    assert.deepEqual(FS_STATE.blocked, [], 'a script attempted a write outside the sandbox');
    for (const [name, fingerprint] of Object.entries(REAL_ARTIFACTS)) {
        assert.equal(fingerprint(), ARTIFACTS_BEFORE[name], `${name} changed during the test run`);
    }
});
