/**
 * Build the static, server-free site for GitHub Pages into ./docs.
 *
 * Pipeline:
 *   1. Inline the rule (.dsl) + weapon (.json) DATA into a generated module
 *      (.build/sources.browser.mjs) — the browser has no filesystem.
 *   2. esbuild-bundle api/lib/pages-api.mjs into docs/dh2-engine.js as a single
 *      classic IIFE, aliasing rules/sources.mjs → the inlined twin from step 1.
 *      The bundle contains the whole engine, DSL, and data; on load it patches
 *      window.fetch so every /api/* call is answered in-process (no server).
 *   3. Copy the UI (ui/*) into docs/, injecting <script src="dh2-engine.js"> as
 *      the first thing in <head> so the fetch patch is installed before the
 *      page's app script runs.
 *   4. Emit .nojekyll (so GitHub Pages serves files verbatim).
 *
 * Run:  npm run build:static     Output: ./docs (deployable to GitHub Pages)
 */
import { build } from 'esbuild';
import { readFileSync, writeFileSync, mkdirSync, rmSync, readdirSync, copyFileSync, statSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join, resolve } from 'path';
import { ruleSources, weaponsJson, RULE_FILES } from '../api/lib/rules/sources.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');
const buildDir = join(root, '.build');
const outDir = join(root, 'docs');
const uiDir = join(root, 'ui');

// ---- 1. inline the data ----------------------------------------------------
mkdirSync(buildDir, { recursive: true });
const browserSources = `// AUTO-GENERATED by scripts/build-static.mjs — do not edit.
// Inlined twin of rules/sources.mjs for the browser (no filesystem).
export const RULE_FILES = ${JSON.stringify(RULE_FILES)};
export const ruleSources = ${JSON.stringify(ruleSources)};
export const weaponsJson = ${JSON.stringify(weaponsJson)};
`;
const browserSourcesPath = join(buildDir, 'sources.browser.mjs');
writeFileSync(browserSourcesPath, browserSources);

// ---- 2. bundle the engine + fetch shim -------------------------------------
rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

await build({
    entryPoints: [join(root, 'api', 'lib', 'pages-api.mjs')],
    bundle: true,
    format: 'iife',
    platform: 'browser',
    target: ['es2020'],
    outfile: join(outDir, 'dh2-engine.js'),
    legalComments: 'none',
    logLevel: 'warning',
    plugins: [{
        // Swap the Node fs-backed data loader for the inlined browser twin.
        name: 'browser-sources',
        setup(b) {
            b.onResolve({ filter: /[\\/]sources\.mjs$/ }, () => ({ path: browserSourcesPath }));
        },
    }],
});

// ---- 3. copy the UI, injecting the engine script ---------------------------
const ENGINE_TAG = '<script src="dh2-engine.js"></script>';
for (const name of readdirSync(uiDir)) {
    const src = join(uiDir, name);
    if (statSync(src).isDirectory()) continue;
    if (name.endsWith('.html')) {
        let html = readFileSync(src, 'utf8');
        // Inject as the FIRST element in <head> so the classic IIFE runs (and
        // patches fetch) before the page's app <script> calls the API.
        if (!html.includes(ENGINE_TAG)) {
            html = html.replace(/<head([^>]*)>/i, `<head$1>\n  ${ENGINE_TAG}`);
        }
        writeFileSync(join(outDir, name), html);
    } else {
        copyFileSync(src, join(outDir, name));
    }
}

// ---- 4. Pages housekeeping -------------------------------------------------
writeFileSync(join(outDir, '.nojekyll'), '');

const files = readdirSync(outDir);
const bundleKb = (statSync(join(outDir, 'dh2-engine.js')).size / 1024).toFixed(0);
console.log(`✓ Static site built → docs/  (${files.length} files; dh2-engine.js ${bundleKb} KB)`);
console.log(`  Deploy: set GitHub Pages source to the docs/ folder, or use the Actions workflow.`);
