/**
 * Bundle the DSL VM into the Foundry walking-skeleton module (ROADMAP Phase 1
 * Lane C):  foundry/dh2-roll-vm/scripts/dh2-vm.js
 *
 * Same recipe as the static Pages build (scripts/build-static.mjs): inline the
 * rule/weapon data via a generated twin of rules/sources.mjs, esbuild-bundle —
 * but as ESM (Foundry loads `esmodules`), not an IIFE, and with the module
 * entry (foundry/dh2-roll-vm/src/main.mjs) instead of the fetch shim.
 *
 * Run:  npm run build:foundry
 * Then symlink/copy foundry/dh2-roll-vm into FoundryVTT/Data/modules/ and
 * enable it in a dark-heresy-2nd world (v12.331 per the Phase 0 baseline).
 */
import { build } from 'esbuild';
import { writeFileSync, mkdirSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join, resolve } from 'path';
import { ruleSources, weaponsJson, RULE_FILES } from '../api/lib/rules/sources.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');
const buildDir = join(root, '.build');
const outFile = join(root, 'foundry', 'dh2-roll-vm', 'scripts', 'dh2-vm.js');

// 1. inline the data (no filesystem inside Foundry)
mkdirSync(buildDir, { recursive: true });
const browserSourcesPath = join(buildDir, 'sources.browser.mjs');
writeFileSync(browserSourcesPath, `// AUTO-GENERATED by scripts/build-foundry.mjs — do not edit.
export const RULE_FILES = ${JSON.stringify(RULE_FILES)};
export const ruleSources = ${JSON.stringify(ruleSources)};
export const weaponsJson = ${JSON.stringify(weaponsJson)};
`);

// 2. bundle the module entry as ESM
mkdirSync(dirname(outFile), { recursive: true });
await build({
    entryPoints: [join(root, 'foundry', 'dh2-roll-vm', 'src', 'main.mjs')],
    bundle: true,
    format: 'esm',
    platform: 'browser',
    target: ['es2020'],
    outfile: outFile,
    legalComments: 'none',
    logLevel: 'warning',
    plugins: [{
        name: 'browser-sources',
        setup(b) {
            b.onResolve({ filter: /[\\/]sources\.mjs$/ }, () => ({ path: browserSourcesPath }));
        },
    }],
});

console.log('✓ Foundry walking skeleton built → foundry/dh2-roll-vm/scripts/dh2-vm.js');
console.log('  Install: copy foundry/dh2-roll-vm/ into FoundryVTT Data/modules/, enable in a dark-heresy-2nd world.');
